/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// AUTO GENERATED BY tools/generate_reflection_metadata_v2.py
// DO NOT EDIT MANUALLY


#ifndef GRAPHICS_EFFECT_GE_FILTER_TYPE_INFO_V2_H
#define GRAPHICS_EFFECT_GE_FILTER_TYPE_INFO_V2_H

#include <type_traits>
#include "ge_filter_type.h"
#include "ge_params_reflection_v2.h"

#include "effect/filter/ge_aibar_shader_filter.h"
#include "effect/filter/ge_bezier_warp_shader_filter.h"
#include "effect/filter/ge_color_gradient_shader_filter.h"
#include "effect/filter/ge_content_light_shader_filter.h"
#include "effect/filter/ge_direction_light_shader_filter.h"
#include "effect/filter/ge_dispersion_shader_filter.h"
#include "effect/filter/ge_displacement_distort_shader_filter.h"
#include "effect/filter/ge_distortion_collapse_filter.h"
#include "effect/filter/ge_edge_light_shader_filter.h"
#include "effect/filter/ge_frosted_glass_blur_shader_filter.h"
#include "effect/filter/ge_frosted_glass_shader_filter.h"
#include "effect/filter/ge_grey_shader_filter.h"
#include "effect/filter/ge_grid_warp_shader_filter.h"
#include "effect/filter/ge_kawase_blur_shader_filter.h"
#include "effect/filter/ge_linear_gradient_blur_shader_filter.h"
#include "effect/filter/ge_magnifier_shader_filter.h"
#include "effect/filter/ge_mask_transition_shader_filter.h"
#include "effect/filter/ge_mesa_blur_shader_filter.h"
#include "effect/filter/ge_sdf_edge_light.h"
#include "effect/filter/ge_sdf_from_image_filter.h"
#include "effect/filter/ge_sound_wave_filter.h"
#include "effect/filter/ge_variable_radius_blur_shader_filter.h"
#include "effect/filter/ge_water_ripple_filter.h"
#include "effect/mask/ge_double_ripple_shader_mask.h"
#include "effect/mask/ge_frame_gradient_shader_mask.h"
#include "effect/mask/ge_image_shader_mask.h"
#include "effect/mask/ge_linear_gradient_shader_mask.h"
#include "effect/mask/ge_pixel_map_shader_mask.h"
#include "effect/mask/ge_radial_gradient_shader_mask.h"
#include "effect/mask/ge_ripple_shader_mask.h"
#include "effect/mask/ge_use_effect_shader_mask.h"
#include "effect/mask/ge_wave_disturb_shader_mask.h"
#include "effect/mask/ge_wave_gradient_shader_mask.h"
#include "effect/shader/ge_aurora_noise_shader.h"
#include "effect/shader/ge_border_light_shader.h"
#include "effect/shader/ge_circle_flowlight_effect.h"
#include "effect/shader/ge_color_gradient_effect.h"
#include "effect/shader/ge_contour_diagonal_flow_light_shader.h"
#include "effect/shader/ge_frosted_glass_effect.h"
#include "effect/shader/ge_particle_circular_halo_shader.h"
#include "effect/shader/ge_sdf_edge_light_shader.h"
#include "effect/shader/ge_wavy_ripple_light_shader.h"
#include "effect/shape/ge_sdf_border_shader.h"
#include "effect/shape/ge_sdf_clip_shader.h"
#include "effect/shape/ge_sdf_color_shader.h"
#include "effect/shape/ge_sdf_pixelmap_shader_shape.h"
#include "effect/shape/ge_sdf_rrect_shader_shape.h"
#include "effect/shape/ge_sdf_shadow_shader.h"
#include "effect/shape/ge_sdf_transform_shader_shape.h"

namespace OHOS {
namespace Rosen {
namespace Drawing {
namespace GEV2 {

// GEFilterTypeInfoV2 - Type information for filter classes
template<typename T, typename = void>
struct GEFilterTypeInfoV2 {
    using FilterClass = T;
    using ParamType = void;
    static constexpr GEFilterType ID = GEFilterType::NONE;
    static constexpr std::string_view Name = "";
};

#define GE_FILTER_TYPE_INFO(_FilterClass, _ParamType) \
    template<> \
    struct GEFilterTypeInfoV2<_FilterClass> { \
        using FilterClass = _FilterClass; \
        using ParamType = _ParamType; \
        static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<_ParamType>::ID; \
        static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<_ParamType>::FilterName; \
    };

// Specializations for filter classes
// Each filter class uses DECLARE_GEFILTER_TYPEFUNC(FilterClass, ParamType)

GE_FILTER_TYPE_INFO(GEAIBarShaderFilter, GEAIBarShaderFilterParams)
GE_FILTER_TYPE_INFO(GEMESABlurShaderFilter, GEMESABlurShaderFilterParams)
GE_FILTER_TYPE_INFO(GEMaskTransitionShaderFilter, GEMaskTransitionShaderFilterParams)
GE_FILTER_TYPE_INFO(GEDisplacementDistortFilter, GEDisplacementDistortFilterParams)
GE_FILTER_TYPE_INFO(GEDistortionCollapseFilter, GEDistortionCollapseFilterParams)
GE_FILTER_TYPE_INFO(GEKawaseBlurShaderFilter, GEKawaseBlurShaderFilterParams)
GE_FILTER_TYPE_INFO(GEEdgeLightShaderFilter, GEEdgeLightShaderFilterParams)
GE_FILTER_TYPE_INFO(GESDFEdgeLight, GESDFEdgeLightFilterParams)
GE_FILTER_TYPE_INFO(GEBezierWarpShaderFilter, GEBezierWarpShaderFilterParams)
GE_FILTER_TYPE_INFO(GEWaterRippleFilter, GEWaterRippleFilterParams)
GE_FILTER_TYPE_INFO(GEContentLightFilter, GEContentLightFilterParams)
GE_FILTER_TYPE_INFO(GEDirectionLightShaderFilter, GEDirectionLightShaderFilterParams)
GE_FILTER_TYPE_INFO(GEDispersionShaderFilter, GEDispersionShaderFilterParams)
GE_FILTER_TYPE_INFO(GEFrostedGlassBlurShaderFilter, GEFrostedGlassBlurShaderFilterParams)
GE_FILTER_TYPE_INFO(GEColorGradientShaderFilter, GEColorGradientShaderFilterParams)
GE_FILTER_TYPE_INFO(GEMagnifierShaderFilter, GEMagnifierShaderFilterParams)
GE_FILTER_TYPE_INFO(GELinearGradientBlurShaderFilter, GELinearGradientBlurShaderFilterParams)
GE_FILTER_TYPE_INFO(GESDFFromImageFilter, GESDFFromImageFilterParams)
GE_FILTER_TYPE_INFO(GEVariableRadiusBlurShaderFilter, GEVariableRadiusBlurShaderFilterParams)
GE_FILTER_TYPE_INFO(GEGreyShaderFilter, GEGreyShaderFilterParams)
GE_FILTER_TYPE_INFO(GEFrostedGlassShaderFilter, GEFrostedGlassShaderFilterParams)
GE_FILTER_TYPE_INFO(GESoundWaveFilter, GESoundWaveFilterParams)
GE_FILTER_TYPE_INFO(GEGridWarpShaderFilter, GEGridWarpShaderFilterParams)
GE_FILTER_TYPE_INFO(GEWaveDisturbanceShaderMask, GEWaveDisturbanceShaderMaskParams)
GE_FILTER_TYPE_INFO(GERippleShaderMask, GERippleShaderMaskParams)
GE_FILTER_TYPE_INFO(GEWaveGradientShaderMask, GEWaveGradientShaderMaskParams)
GE_FILTER_TYPE_INFO(GEImageShaderMask, GEImageMaskParams)
GE_FILTER_TYPE_INFO(GELinearGradientShaderMask, GELinearGradientShaderMaskParams)
GE_FILTER_TYPE_INFO(GERadialGradientShaderMask, GERadialGradientShaderMaskParams)
GE_FILTER_TYPE_INFO(GEDoubleRippleShaderMask, GEDoubleRippleShaderMaskParams)
GE_FILTER_TYPE_INFO(GEUseEffectShaderMask, GEUseEffectMaskParams)
GE_FILTER_TYPE_INFO(GEFrameGradientShaderMask, GEFrameGradientMaskParams)
GE_FILTER_TYPE_INFO(GEPixelMapShaderMask, GEPixelMapMaskParams)
GE_FILTER_TYPE_INFO(GEWavyRippleLightShader, GEWavyRippleLightShaderParams)
GE_FILTER_TYPE_INFO(GEAuroraNoiseShader, GEAuroraNoiseShaderParams)
GE_FILTER_TYPE_INFO(GESDFEdgeLightShader, GESDFEdgeLightEffectParams)
GE_FILTER_TYPE_INFO(GEFrostedGlassEffect, GEFrostedGlassEffectParams)
GE_FILTER_TYPE_INFO(GEParticleCircularHaloShader, GEParticleCircularHaloShaderParams)
GE_FILTER_TYPE_INFO(GEContourDiagonalFlowLightShader, GEContentDiagonalFlowLightShaderParams)
GE_FILTER_TYPE_INFO(GECircleFlowlightEffect, GECircleFlowlightEffectParams)
GE_FILTER_TYPE_INFO(GEColorGradientEffect, GEXColorGradientEffectParams)
GE_FILTER_TYPE_INFO(GEBorderLightShader, GEBorderLightShaderParams)
GE_FILTER_TYPE_INFO(GESDFPixelmapShaderShape, GESDFPixelmapShapeParams)
GE_FILTER_TYPE_INFO(GESDFTransformShaderShape, GESDFTransformShapeParams)
GE_FILTER_TYPE_INFO(GESDFShadowShader, GESDFShadowShaderParams)
GE_FILTER_TYPE_INFO(GESDFBorderShader, GESDFBorderShaderParams)
GE_FILTER_TYPE_INFO(GESDFRRectShaderShape, GESDFRRectShapeParams)
GE_FILTER_TYPE_INFO(GESDFColorShader, GESDFColorShaderParams)
GE_FILTER_TYPE_INFO(GESDFClipShader, GESDFClipShaderParams)

#undef GE_FILTER_TYPE_INFO

} // namespace GEV2
} // namespace Drawing
} // namespace Rosen
} // namespace OHOS

#endif // GRAPHICS_EFFECT_GE_FILTER_TYPE_INFO_V2_H