/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// AUTO GENERATED BY tools/generate_reflection_metadata_v2.py
// DO NOT EDIT MANUALLY


#ifndef GRAPHICS_EFFECT_GE_FILTER_TYPE_INFO_V2_H
#define GRAPHICS_EFFECT_GE_FILTER_TYPE_INFO_V2_H

#include <type_traits>
#include "ge_filter_type.h"
#include "ge_params_reflection_v2.h"

#include "effect/filter/ge_aibar_shader_filter.h"
#include "effect/filter/ge_bezier_warp_shader_filter.h"
#include "effect/filter/ge_color_gradient_shader_filter.h"
#include "effect/filter/ge_content_light_shader_filter.h"
#include "effect/filter/ge_direction_light_shader_filter.h"
#include "effect/filter/ge_dispersion_shader_filter.h"
#include "effect/filter/ge_displacement_distort_shader_filter.h"
#include "effect/filter/ge_edge_light_shader_filter.h"
#include "effect/filter/ge_frosted_glass_blur_shader_filter.h"
#include "effect/filter/ge_frosted_glass_shader_filter.h"
#include "effect/filter/ge_grey_shader_filter.h"
#include "effect/filter/ge_grid_warp_shader_filter.h"
#include "effect/filter/ge_kawase_blur_shader_filter.h"
#include "effect/filter/ge_linear_gradient_blur_shader_filter.h"
#include "effect/filter/ge_magnifier_shader_filter.h"
#include "effect/filter/ge_mask_transition_shader_filter.h"
#include "effect/filter/ge_mesa_blur_shader_filter.h"
#include "effect/filter/ge_sdf_edge_light.h"
#include "effect/filter/ge_sdf_from_image_filter.h"
#include "effect/filter/ge_sound_wave_filter.h"
#include "effect/filter/ge_variable_radius_blur_shader_filter.h"
#include "effect/filter/ge_water_ripple_filter.h"
#include "effect/mask/ge_double_ripple_shader_mask.h"
#include "effect/mask/ge_frame_gradient_shader_mask.h"
#include "effect/mask/ge_image_shader_mask.h"
#include "effect/mask/ge_linear_gradient_shader_mask.h"
#include "effect/mask/ge_pixel_map_shader_mask.h"
#include "effect/mask/ge_radial_gradient_shader_mask.h"
#include "effect/mask/ge_ripple_shader_mask.h"
#include "effect/mask/ge_use_effect_shader_mask.h"
#include "effect/mask/ge_wave_disturb_shader_mask.h"
#include "effect/mask/ge_wave_gradient_shader_mask.h"
#include "effect/shader/ge_aurora_noise_shader.h"
#include "effect/shader/ge_border_light_shader.h"
#include "effect/shader/ge_circle_flowlight_effect.h"
#include "effect/shader/ge_color_gradient_effect.h"
#include "effect/shader/ge_contour_diagonal_flow_light_shader.h"
#include "effect/shader/ge_particle_circular_halo_shader.h"
#include "effect/shader/ge_wavy_ripple_light_shader.h"
#include "effect/shape/ge_sdf_border_shader.h"
#include "effect/shape/ge_sdf_clip_shader.h"
#include "effect/shape/ge_sdf_color_shader.h"
#include "effect/shape/ge_sdf_pixelmap_shader_shape.h"
#include "effect/shape/ge_sdf_rrect_shader_shape.h"
#include "effect/shape/ge_sdf_shadow_shader.h"
#include "effect/shape/ge_sdf_transform_shader_shape.h"

namespace OHOS {
namespace Rosen {
namespace Drawing {
namespace GEV2 {

// GEFilterTypeInfoV2 - Type information for filter classes
template<typename T, typename = void>
struct GEFilterTypeInfoV2 {
    using FilterClass = T;
    using ParamType = void;
    static constexpr GEFilterType ID = GEFilterType::NONE;
    static constexpr std::string_view Name = "";
};

// Specializations for filter classes
// Each filter class uses DECLARE_GEFILTER_TYPEFUNC(FilterClass, ParamType)

template<>
struct GEFilterTypeInfoV2<GEAIBarShaderFilter> {
    using FilterClass = GEAIBarShaderFilter;
    using ParamType = Drawing::GEAIBarShaderFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEAIBarShaderFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEAIBarShaderFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEMESABlurShaderFilter> {
    using FilterClass = GEMESABlurShaderFilter;
    using ParamType = Drawing::GEMESABlurShaderFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEMESABlurShaderFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEMESABlurShaderFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEMaskTransitionShaderFilter> {
    using FilterClass = GEMaskTransitionShaderFilter;
    using ParamType = Drawing::GEMaskTransitionShaderFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEMaskTransitionShaderFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEMaskTransitionShaderFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEDisplacementDistortFilter> {
    using FilterClass = GEDisplacementDistortFilter;
    using ParamType = Drawing::GEDisplacementDistortFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEDisplacementDistortFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEDisplacementDistortFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEKawaseBlurShaderFilter> {
    using FilterClass = GEKawaseBlurShaderFilter;
    using ParamType = Drawing::GEKawaseBlurShaderFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEKawaseBlurShaderFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEKawaseBlurShaderFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEEdgeLightShaderFilter> {
    using FilterClass = GEEdgeLightShaderFilter;
    using ParamType = Drawing::GEEdgeLightShaderFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEEdgeLightShaderFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEEdgeLightShaderFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GESDFEdgeLight> {
    using FilterClass = GESDFEdgeLight;
    using ParamType = Drawing::GESDFEdgeLightFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GESDFEdgeLightFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GESDFEdgeLightFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEBezierWarpShaderFilter> {
    using FilterClass = GEBezierWarpShaderFilter;
    using ParamType = Drawing::GEBezierWarpShaderFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEBezierWarpShaderFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEBezierWarpShaderFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEWaterRippleFilter> {
    using FilterClass = GEWaterRippleFilter;
    using ParamType = Drawing::GEWaterRippleFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEWaterRippleFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEWaterRippleFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEContentLightFilter> {
    using FilterClass = GEContentLightFilter;
    using ParamType = Drawing::GEContentLightFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEContentLightFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEContentLightFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEDirectionLightShaderFilter> {
    using FilterClass = GEDirectionLightShaderFilter;
    using ParamType = Drawing::GEDirectionLightShaderFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEDirectionLightShaderFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEDirectionLightShaderFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEDispersionShaderFilter> {
    using FilterClass = GEDispersionShaderFilter;
    using ParamType = Drawing::GEDispersionShaderFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEDispersionShaderFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEDispersionShaderFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEFrostedGlassBlurShaderFilter> {
    using FilterClass = GEFrostedGlassBlurShaderFilter;
    using ParamType = Drawing::GEFrostedGlassBlurShaderFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEFrostedGlassBlurShaderFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEFrostedGlassBlurShaderFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEColorGradientShaderFilter> {
    using FilterClass = GEColorGradientShaderFilter;
    using ParamType = Drawing::GEColorGradientShaderFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEColorGradientShaderFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEColorGradientShaderFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEMagnifierShaderFilter> {
    using FilterClass = GEMagnifierShaderFilter;
    using ParamType = Drawing::GEMagnifierShaderFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEMagnifierShaderFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEMagnifierShaderFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GELinearGradientBlurShaderFilter> {
    using FilterClass = GELinearGradientBlurShaderFilter;
    using ParamType = Drawing::GELinearGradientBlurShaderFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GELinearGradientBlurShaderFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GELinearGradientBlurShaderFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GESDFFromImageFilter> {
    using FilterClass = GESDFFromImageFilter;
    using ParamType = Drawing::GESDFFromImageFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GESDFFromImageFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GESDFFromImageFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEVariableRadiusBlurShaderFilter> {
    using FilterClass = GEVariableRadiusBlurShaderFilter;
    using ParamType = Drawing::GEVariableRadiusBlurShaderFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEVariableRadiusBlurShaderFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEVariableRadiusBlurShaderFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEGreyShaderFilter> {
    using FilterClass = GEGreyShaderFilter;
    using ParamType = Drawing::GEGreyShaderFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEGreyShaderFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEGreyShaderFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEFrostedGlassShaderFilter> {
    using FilterClass = GEFrostedGlassShaderFilter;
    using ParamType = Drawing::GEFrostedGlassShaderFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEFrostedGlassShaderFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEFrostedGlassShaderFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GESoundWaveFilter> {
    using FilterClass = GESoundWaveFilter;
    using ParamType = Drawing::GESoundWaveFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GESoundWaveFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GESoundWaveFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEGridWarpShaderFilter> {
    using FilterClass = GEGridWarpShaderFilter;
    using ParamType = Drawing::GEGridWarpShaderFilterParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEGridWarpShaderFilterParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEGridWarpShaderFilterParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEWaveDisturbanceShaderMask> {
    using FilterClass = GEWaveDisturbanceShaderMask;
    using ParamType = GEWaveDisturbanceShaderMaskParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<GEWaveDisturbanceShaderMaskParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<GEWaveDisturbanceShaderMaskParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GERippleShaderMask> {
    using FilterClass = GERippleShaderMask;
    using ParamType = GERippleShaderMaskParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<GERippleShaderMaskParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<GERippleShaderMaskParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEWaveGradientShaderMask> {
    using FilterClass = GEWaveGradientShaderMask;
    using ParamType = GEWaveGradientShaderMaskParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<GEWaveGradientShaderMaskParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<GEWaveGradientShaderMaskParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEImageShaderMask> {
    using FilterClass = GEImageShaderMask;
    using ParamType = GEImageMaskParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<GEImageMaskParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<GEImageMaskParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GELinearGradientShaderMask> {
    using FilterClass = GELinearGradientShaderMask;
    using ParamType = GELinearGradientShaderMaskParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<GELinearGradientShaderMaskParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<GELinearGradientShaderMaskParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GERadialGradientShaderMask> {
    using FilterClass = GERadialGradientShaderMask;
    using ParamType = GERadialGradientShaderMaskParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<GERadialGradientShaderMaskParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<GERadialGradientShaderMaskParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEDoubleRippleShaderMask> {
    using FilterClass = GEDoubleRippleShaderMask;
    using ParamType = GEDoubleRippleShaderMaskParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<GEDoubleRippleShaderMaskParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<GEDoubleRippleShaderMaskParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEUseEffectShaderMask> {
    using FilterClass = GEUseEffectShaderMask;
    using ParamType = GEUseEffectMaskParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<GEUseEffectMaskParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<GEUseEffectMaskParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEFrameGradientShaderMask> {
    using FilterClass = GEFrameGradientShaderMask;
    using ParamType = GEFrameGradientMaskParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<GEFrameGradientMaskParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<GEFrameGradientMaskParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEPixelMapShaderMask> {
    using FilterClass = GEPixelMapShaderMask;
    using ParamType = GEPixelMapMaskParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<GEPixelMapMaskParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<GEPixelMapMaskParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEWavyRippleLightShader> {
    using FilterClass = GEWavyRippleLightShader;
    using ParamType = Drawing::GEWavyRippleLightShaderParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEWavyRippleLightShaderParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEWavyRippleLightShaderParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEAuroraNoiseShader> {
    using FilterClass = GEAuroraNoiseShader;
    using ParamType = Drawing::GEAuroraNoiseShaderParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEAuroraNoiseShaderParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEAuroraNoiseShaderParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEParticleCircularHaloShader> {
    using FilterClass = GEParticleCircularHaloShader;
    using ParamType = Drawing::GEParticleCircularHaloShaderParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEParticleCircularHaloShaderParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEParticleCircularHaloShaderParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEContourDiagonalFlowLightShader> {
    using FilterClass = GEContourDiagonalFlowLightShader;
    using ParamType = Drawing::GEContentDiagonalFlowLightShaderParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEContentDiagonalFlowLightShaderParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEContentDiagonalFlowLightShaderParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GECircleFlowlightEffect> {
    using FilterClass = GECircleFlowlightEffect;
    using ParamType = Drawing::GECircleFlowlightEffectParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GECircleFlowlightEffectParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GECircleFlowlightEffectParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEColorGradientEffect> {
    using FilterClass = GEColorGradientEffect;
    using ParamType = Drawing::GEXColorGradientEffectParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEXColorGradientEffectParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEXColorGradientEffectParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GEBorderLightShader> {
    using FilterClass = GEBorderLightShader;
    using ParamType = Drawing::GEBorderLightShaderParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GEBorderLightShaderParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GEBorderLightShaderParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GESDFPixelmapShaderShape> {
    using FilterClass = GESDFPixelmapShaderShape;
    using ParamType = GESDFPixelmapShapeParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<GESDFPixelmapShapeParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<GESDFPixelmapShapeParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GESDFTransformShaderShape> {
    using FilterClass = GESDFTransformShaderShape;
    using ParamType = GESDFTransformShapeParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<GESDFTransformShapeParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<GESDFTransformShapeParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GESDFShadowShader> {
    using FilterClass = GESDFShadowShader;
    using ParamType = Drawing::GESDFShadowShaderParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GESDFShadowShaderParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GESDFShadowShaderParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GESDFBorderShader> {
    using FilterClass = GESDFBorderShader;
    using ParamType = Drawing::GESDFBorderShaderParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GESDFBorderShaderParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GESDFBorderShaderParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GESDFRRectShaderShape> {
    using FilterClass = GESDFRRectShaderShape;
    using ParamType = Drawing::GESDFRRectShapeParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GESDFRRectShapeParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GESDFRRectShapeParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GESDFColorShader> {
    using FilterClass = GESDFColorShader;
    using ParamType = Drawing::GESDFColorShaderParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GESDFColorShaderParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GESDFColorShaderParams>::FilterName;
};

template<>
struct GEFilterTypeInfoV2<GESDFClipShader> {
    using FilterClass = GESDFClipShader;
    using ParamType = Drawing::GESDFClipShaderParams;
    static constexpr GEFilterType ID = GEFilterParamsTypeInfoV2<Drawing::GESDFClipShaderParams>::ID;
    static constexpr std::string_view Name = GEFilterParamsTypeInfoV2<Drawing::GESDFClipShaderParams>::FilterName;
};

} // namespace GEV2
} // namespace Drawing
} // namespace Rosen
} // namespace OHOS

#endif // GRAPHICS_EFFECT_GE_FILTER_TYPE_INFO_V2_H