#!/usr/bin/env python3
"""
Generate C++ static reflection metadata from .params files (Improved Version).

This script provides a best-in-effort C++ parser with:
- Proper tokenization (handling comments, strings, char literals, etc.)
- Flexible struct parsing
- C#/Rust-style attribute parsing (e.g., [[ge::params(type=AIBAR, name="AIBAR")]])
- Extensible design for future enhancements
"""

import sys
import argparse
import json
from pathlib import Path
from typing import Dict, List, Tuple, Optional

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

# Import parser modules
from tool.effectgen.cpp_tokenizer import CppTokenizer
from tool.effectgen.cpp_parser import CppParser, StructInfo, FieldInfo

# Copyright header for generated files
COPYRIGHT_HEADER = """/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// AUTO GENERATED BY tools/generate_reflection_metadata_v2.py
// DO NOT EDIT MANUALLY
"""


def load_config(config_path: Path) -> Dict[str, str]:
    """Load type aliases from config.json."""
    type_aliases = {}
    try:
        with open(config_path, 'r', encoding='utf-8') as f:
            config = json.load(f)
            type_aliases = config.get('type_aliases', {})
    except FileNotFoundError:
        print(f"Warning: Config file not found at {config_path}", file=sys.stderr)
    except json.JSONDecodeError as e:
        print(f"Warning: Failed to parse config file: {e}", file=sys.stderr)
    return type_aliases


def normalize_type(type_str: str, type_aliases: Dict[str, str]) -> str:
    """Normalize a type string using type aliases and removing unnecessary spaces.

    Spaces are removed except:
    - Between type qualifiers (const, volatile, mutable) and next token
    - Between type modifiers (unsigned, signed, short, long) and next token
    - After commas inside template parameters
    """
    # First apply type aliases
    type_str = type_aliases.get(type_str, type_str)

    # Keywords that should preserve space after them
    preserve_space_keywords = {
        'const', 'volatile', 'mutable',
        'unsigned', 'signed', 'short', 'long'
    }

    import re

    # Tokenize type string, preserving structure
    # We need to track template depth to know when we're inside <...>
    tokens = []
    depth = 0
    i = 0
    while i < len(type_str):
        ch = type_str[i]

        # Track template depth
        if ch == '<':
            depth += 1
            tokens.append(ch)
            i += 1
        elif ch == '>':
            depth = max(0, depth - 1)
            tokens.append(ch)
            i += 1
        elif ch == ',':
            # Commas are preserved inside templates
            tokens.append(ch)
            i += 1
        elif ch in [' ', '\t', '\n']:
            # Collect all whitespace
            ws = ch
            i += 1
            while i < len(type_str) and type_str[i] in [' ', '\t', '\n']:
                ws += type_str[i]
                i += 1
            tokens.append(('ws', ws))
        elif ch in ['*', '&']:
            tokens.append(ch)
            i += 1
        elif ch == ':' and i + 1 < len(type_str) and type_str[i + 1] == ':':
            tokens.append('::')
            i += 2
        else:
            # Collect identifier/keyword
            ident = ch
            i += 1
            while i < len(type_str) and (type_str[i].isalnum() or type_str[i] == '_'):
                ident += type_str[i]
                i += 1
            tokens.append(ident)

    # Build normalized string
    result = []
    i = 0
    while i < len(tokens):
        token = tokens[i]

        # Skip whitespace
        if isinstance(token, tuple) and token[0] == 'ws':
            i += 1
            continue

        # Add token
        result.append(token)

        # Check if we need to preserve space after this token
        if token == ',':
            # Add a space after comma (for template parameters)
            result.append(' ')
        elif token in preserve_space_keywords:
            # Look ahead to see if there's a non-whitespace token
            j = i + 1
            while j < len(tokens):
                next_token = tokens[j]
                if isinstance(next_token, tuple) and next_token[0] == 'ws':
                    j += 1
                    continue
                break

            if j < len(tokens) and tokens[j] not in ['<', '>', '::', '*', '&', ',']:
                # Add a space
                result.append(' ')

        i += 1

    return ''.join(result)


def parse_def_file(file_path: Path, report_errors: bool = True) -> Optional[StructInfo]:
    """Parse a .def file and extract struct information."""
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Tokenize
    tokenizer = CppTokenizer(content)
    tokens = tokenizer.tokenize()

    # Parse
    parser = CppParser(tokens, str(file_path))
    structs = parser.parse()

    # Report errors if requested
    if report_errors and parser.errors:
        for error in parser.errors:
            print(f"  {error}", file=sys.stderr)

    # Return the first (and typically only) struct
    if structs:
        return structs[0]
    return None


def to_upper_case(name: str) -> str:
    """Convert camelCase or snake_case to UPPER_CASE."""
    if name.endswith('_'):
        name = name[:-1]
    result = []
    for c in name:
        if c.isupper():
            if result:
                result.append('_')
            result.append(c)
        else:
            result.append(c.upper())
    return ''.join(result)


def to_pascal_case(name: str) -> str:
    """Convert snake_case or camelCase to PascalCase.

    Examples:
        propName -> PropName
        prop_name -> PropName
        _propName -> PropName (strip leading underscore)
    """
    # Remove trailing underscore
    if name.endswith('_'):
        name = name[:-1]
    # Remove leading underscore
    if name.startswith('_'):
        name = name[1:]

    if not name:
        return name

    # Convert to PascalCase
    result = []
    capitalize_next = True
    for c in name:
        if c == '_':
            capitalize_next = True
        elif capitalize_next:
            result.append(c.upper())
            capitalize_next = False
        else:
            result.append(c)
    return ''.join(result)


def to_member_tag_name(enum_type: str, field_name: str, index: Optional[int] = None) -> str:
    """Generate GEParamsMemberTag enum name.

    Args:
        enum_type: The enum type (e.g., BEZIER_WARP)
        field_name: The field name (e.g., destinationPatch)
        index: Optional index for array accessor fields (e.g., 0 for destinationPatch[0])
    """
    field_upper = to_upper_case(field_name)
    if index is not None:
        return f"{enum_type}_{field_upper}{index}"
    return f"{enum_type}_{field_upper}"


def get_effective_prop_name(field: FieldInfo, filter_name: str, index: Optional[int] = None) -> str:
    """Get the effective property name for a field.

    Args:
        field: The field info
        filter_name: The filter name
        index: Optional index for array accessor fields

    Note:
        Uses PascalCase as default for fields without explicit [[ge::prop]].
        Fields that need UPPER_CASE naming should use explicit [[ge::prop("UPPER_CASE_NAME")]].
    """
    if field.prop_name:
        if index is not None:
            return f"{field.prop_name}{index}"
        return field.prop_name
    # Use PascalCase as default for fields without explicit prop
    base_name = to_pascal_case(field.name)
    if index is not None:
        return f"{filter_name}_{base_name}{index}"
    return f"{filter_name}_{base_name}"


def iterate_field_tags(struct: StructInfo, field: FieldInfo):
    """Helper to iterate over all tags for a field.

    Yields tuples of (tag_name, prop_name, is_array_element, array_index).
    For array elements, array_index is the element index.
    For whole-field accessors, is_array_element is False and array_index is None.
    """
    enum_type = struct.enum_type

    if field.prop_attributes:
        for prop_attr in field.prop_attributes:
            if prop_attr.array_accessor_length is not None:
                # Generate tags for each array element
                for i in range(prop_attr.array_accessor_length):
                    tag_name = to_member_tag_name(enum_type, field.name, i)
                    prop_name = f"{prop_attr.name}{i}"
                    yield (tag_name, prop_name, True, i)
            else:
                # Single tag for whole-field accessor
                tag_name = to_member_tag_name(enum_type, field.name)
                prop_name = prop_attr.name
                yield (tag_name, prop_name, False, None)
    else:
        # No prop_attributes: single tag for field
        tag_name = to_member_tag_name(enum_type, field.name)
        prop_name = get_effective_prop_name(field, struct.filter_name)
        yield (tag_name, prop_name, False, None)


def generate_member_enums(structs: List[StructInfo]) -> Tuple[str, Dict[str, Tuple[int, int, str]]]:
    """Generate GEParamsMemberTag enum."""
    output = []

    # Generate member tag enum
    output.append("enum class GEParamsMemberTag : uint32_t {")
    output.append("    INVALID = 0,")

    tag_count = 1
    struct_tag_ranges = {}
    for struct in structs:
        first_tag = tag_count
        enum_start = struct.enum_type

        for field in struct.fields:
            for tag_name, _, _, _ in iterate_field_tags(struct, field):
                output.append(f"    {tag_name},")
                tag_count += 1

        last_tag = tag_count - 1
        struct_tag_ranges[struct.name] = (first_tag, last_tag, enum_start)

    output.append("};")
    output.append("")
    return '\n'.join(output), struct_tag_ranges


def generate_struct_tag_ranges_decl(structs: List[StructInfo], type_aliases: Dict[str, str]) -> str:
    """Generate GEParamsMemberHelper class declaration."""
    output = []

    output.append("")
    output.append("// FilterType to TagRange mapping")
    output.append("struct GEParamsMemberTagRange {")
    output.append("    GEParamsMemberTag RangeStart;")
    output.append("    GEParamsMemberTag RangeEnd;")
    output.append("};")
    output.append("")

    output.append("// Static helper class for params member tag operations")
    output.append("class GEParamsMemberHelper {")
    output.append("public:")
    output.append("    // Get tag range for a given FilterType (using switch for performance)")
    output.append("    static std::optional<GEParamsMemberTagRange> GetParamsMemberTagRange(GEFilterType filterType);")

    output.append("")
    output.append("    // Convert GEParamsMemberTag to corresponding GEFilterType")
    output.append("    static GEFilterType GetFilterTypeFromTag(GEParamsMemberTag tag);")

    output.append("")
    output.append("    // Set params member by tag using overloaded functions (reduces binary bloat)")
    output.append("    // All implementations are in the .cpp file")
    output.append(generate_set_params_member_overloads_decl(structs, type_aliases))

    output.append("};")
    output.append("")

    return '\n'.join(output)


def generate_struct_tag_ranges_impl(structs: List[StructInfo]) -> str:
    """Generate GEParamsMemberHelper::GetParamsMemberTagRange() implementation."""
    output = []

    output.append("std::optional<GEParamsMemberTagRange> GEParamsMemberHelper::GetParamsMemberTagRange(GEFilterType filterType)")
    output.append("{")
    output.append("    switch (filterType) {")

    output.append("#define GE_GET_TAG_RANGE_CASE(EnumType, FirstTag, LastTag) \\")
    output.append("    case GEFilterType::EnumType: \\")
    output.append("        return {{ GEParamsMemberTag::FirstTag, GEParamsMemberTag::LastTag }};")
    output.append("")

    for struct in structs:
        enum_type = struct.enum_type
        # Get first and last tag names using helper
        first_tag = None
        last_tag = None
        for field in struct.fields:
            for tag_name, _, _, _ in iterate_field_tags(struct, field):
                if first_tag is None:
                    first_tag = tag_name
                last_tag = tag_name

        if first_tag and last_tag:
            output.append(f"        GE_GET_TAG_RANGE_CASE({enum_type}, {first_tag}, {last_tag})")

    output.append("        default:")
    output.append("            return std::nullopt;")
    output.append("        }")
    output.append("}")
    output.append("")
    output.append("#undef GE_GET_TAG_RANGE_CASE")
    output.append("")

    return '\n'.join(output)


def generate_get_filter_type_from_tag_impl(structs: List[StructInfo]) -> str:
    """Generate GEParamsMemberHelper::GetFilterTypeFromTag() implementation."""
    output = []

    output.append("GEFilterType GEParamsMemberHelper::GetFilterTypeFromTag(GEParamsMemberTag tag)")
    output.append("{")
    output.append("    switch (tag) {")

    for struct in structs:
        enum_type = struct.enum_type
        for field in struct.fields:
            for tag_name, _, _, _ in iterate_field_tags(struct, field):
                output.append(f"        case GEParamsMemberTag::{tag_name}:")
                output.append(f"            return GEFilterType::{enum_type};")

    output.append("        default:")
    output.append("            return GEFilterType::NONE;")
    output.append("    }")
    output.append("}")
    output.append("")

    return '\n'.join(output)


def generate_set_params_member_overloads_impl(structs: List[StructInfo], type_aliases: Dict[str, str]) -> str:
    """Generate overloaded SetParamsMemberByTag function implementations."""
    output = []

    output.append("// Helper macro to validate and set parameter")
    output.append("#define GE_VALIDATE_AND_SET(Tag, Value) \\")
    output.append("    case GEParamsMemberTag::Tag: { \\")
    output.append("        using ExpectedType = GEParamsFieldAccessor<GEParamsMemberTag::Tag>::ParamsType; \\")
    output.append("        using FieldType = GEParamsFieldAccessor<GEParamsMemberTag::Tag>::FieldType; \\")
    output.append("        auto unboxed = GEFilterParams::Unbox<ExpectedType>(params); \\")
    output.append("        if (!unboxed.has_value()) { \\")
    output.append("            return; \\")
    output.append("        } \\")
    output.append("        auto& actualParams = *unboxed; \\")
    output.append("        auto transformed = GEParamsValueTransformer<GEParamsMemberTag::Tag, FieldType>::Transform(Value); \\")
    output.append("        GEParamsFieldAccessor<GEParamsMemberTag::Tag>::Set(actualParams, transformed); \\")
    output.append("        break; \\")
    output.append("    }")
    output.append("")

    # Group tags by their effective type (considering array_accessor_type)
    type_to_tags = {}
    for struct in structs:
        for field in struct.fields:
            for tag_name, _, is_array_elem, array_idx in iterate_field_tags(struct, field):
                if is_array_elem and field.prop_attributes:
                    # For array elements, find the prop attribute with array_accessor_length
                    for prop_attr in field.prop_attributes:
                        if prop_attr.array_accessor_length is not None:
                            if prop_attr.array_accessor_type:
                                # Use specified array_accessor_type
                                effective_type = prop_attr.array_accessor_type
                            else:
                                # Fallback to field type (array type)
                                effective_type = field.type
                            break
                else:
                    # Regular field
                    effective_type = field.type

                # Normalize type using type aliases
                normalized_type = normalize_type(effective_type, type_aliases)

                if normalized_type not in type_to_tags:
                    type_to_tags[normalized_type] = []
                type_to_tags[normalized_type].append((tag_name, struct.name, field.name))

    # Generate implementations for each type
    for field_type, tags in type_to_tags.items():
        output.append(f"void GEParamsMemberHelper::SetParamsMemberByTag(const std::shared_ptr<GEFilterParams>& params,")
        output.append(f"                                                GEParamsMemberTag tag, const {field_type}& value)")
        output.append("{")
        output.append("    if (!params) {")
        output.append("        return;")
        output.append("    }")
        output.append("")
        output.append("    auto expectedFilterType = GetFilterTypeFromTag(tag);")
        output.append("    if (params->GetType() != expectedFilterType) {")
        output.append("        return;")
        output.append("    }")
        output.append("")
        output.append("    switch (tag) {")

        for tag_name, struct_name, field_name in tags:
            output.append(f"        GE_VALIDATE_AND_SET({tag_name}, value)")

        output.append("        default:")
        output.append("            break;")
        output.append("    }")
        output.append("}")
        output.append("")

    output.append("#undef GE_VALIDATE_AND_SET")
    output.append("")

    return '\n'.join(output)


def generate_filter_params_type_info(structs: List[StructInfo]) -> str:
    """Generate GEFilterParamsTypeInfo template specializations."""
    output = []

    output.append("// GEFilterParamsTypeInfo template specializations")
    output.append("// Provides FilterType ID and FilterName for each params type")
    output.append("template<typename T>")
    output.append("struct GEFilterParamsTypeInfo {")
    output.append("    using Self = T;")
    output.append("    static constexpr GEFilterType ID = GEFilterType::NONE;")
    output.append("    static constexpr std::string_view FilterName = \"\";")
    output.append("};")
    output.append("")

    output.append("// Helper macro for GEParamsTypeInfo specializations")
    output.append("#define GE_PARAMS_TYPE_INFO(Struct, FilterTypeEnum, FilterNameStr) \\")
    output.append("    template<> \\")
    output.append("    struct GEFilterParamsTypeInfo<Struct> { \\")
    output.append("        using Self = Struct; \\")
    output.append("        static constexpr GEFilterType ID = GEFilterType::FilterTypeEnum; \\")
    output.append("        static constexpr std::string_view FilterName = #FilterNameStr; \\")
    output.append("    };")
    output.append("")

    for struct in structs:
        enum_type = struct.enum_type
        struct_name = struct.name
        filter_name = struct.filter_name
        output.append(f"GE_PARAMS_TYPE_INFO({struct_name}, {enum_type}, {filter_name})")

    output.append("")
    output.append("#undef GE_PARAMS_TYPE_INFO")
    output.append("")

    return '\n'.join(output)


def generate_type_traits(structs: List[StructInfo]) -> str:
    """Generate type traits for parameter structs."""
    output = []

    output.append("// Type traits for accessing struct fields")
    output.append("template<GEParamsMemberTag Tag>")
    output.append("struct GEParamsFieldAccessor;")
    output.append("")

    output.append("// Helper macro for generating field accessors")
    output.append("#define GE_PARAMS_FIELD_ACCESSOR(Struct, Field, Tag, PropName) \\")
    output.append("    template<> \\")
    output.append("    struct GEParamsFieldAccessor<GEParamsMemberTag::Tag> { \\")
    output.append("        using ParamsType = Struct; \\")
    output.append("        using FieldType = decltype(Struct::Field); \\")
    output.append("        static constexpr const char name[] = #PropName; \\")
    output.append("        static FieldType& Get(ParamsType& params) { return params.Field; } \\")
    output.append("        static const FieldType& Get(const ParamsType& params) { return params.Field; } \\")
    output.append("        static void Set(ParamsType& params, const FieldType& value) { params.Field = value; } \\")
    output.append("    };")
    output.append("")

    # Helper macro for array element accessors
    output.append("// Helper macro for generating array element field accessors")
    output.append("#define GE_PARAMS_ARRAY_ELEMENT_ACCESSOR(Struct, Field, Index, Tag, PropName) \\")
    output.append("    template<> \\")
    output.append("    struct GEParamsFieldAccessor<GEParamsMemberTag::Tag> { \\")
    output.append("        using ParamsType = Struct; \\")
    output.append("        using FieldType = typename decltype(Struct::Field)::value_type; \\")
    output.append("        static constexpr const char* name = #PropName; \\")
    output.append("        static FieldType& Get(ParamsType& params) { return params.Field[Index]; } \\")
    output.append("        static const FieldType& Get(const ParamsType& params) { return params.Field[Index]; } \\")
    output.append("        static void Set(ParamsType& params, const FieldType& value) { params.Field[Index] = value; } \\")
    output.append("    };")
    output.append("")

    for struct in structs:
        for field in struct.fields:
            for tag_name, prop_name, is_array_elem, array_idx in iterate_field_tags(struct, field):
                if is_array_elem:
                    output.append(f"GE_PARAMS_ARRAY_ELEMENT_ACCESSOR({struct.name}, {field.name}, {array_idx}, {tag_name}, {prop_name})")
                else:
                    output.append(f"GE_PARAMS_FIELD_ACCESSOR({struct.name}, {field.name}, {tag_name}, {prop_name})")

    output.append("")
    output.append("#undef GE_PARAMS_FIELD_ACCESSOR")
    output.append("#undef GE_PARAMS_ARRAY_ELEMENT_ACCESSOR")
    output.append("")

    return '\n'.join(output)


def generate_set_member_cases(structs: List[StructInfo]) -> str:
    """Generate switch cases for SetParamsMemberByTag template function."""
    output = []

    output.append("#define GE_SET_MEMBER_CASE(Tag) \\")
    output.append("    case GEParamsMemberTag::Tag: \\")
    output.append("        if constexpr (std::is_same_v<ParamsType, GEParamsFieldAccessor<GEParamsMemberTag::Tag>::ParamsType>) {{ \\")
    output.append("            auto transformed = GEParamsValueTransformer<GEParamsMemberTag::Tag, T>::Transform(value); \\")
    output.append("            GEParamsFieldAccessor<GEParamsMemberTag::Tag>::Set(params, transformed); \\")
    output.append("        }} \\")
    output.append("        break;")
    output.append("")

    for struct in structs:
        for field in struct.fields:
            for tag_name, _, _, _ in iterate_field_tags(struct, field):
                output.append(f"        GE_SET_MEMBER_CASE({tag_name})")

    output.append("")
    output.append("#undef GE_SET_MEMBER_CASE")
    output.append("")

    return '\n'.join(output)


def generate_set_params_member_overloads_decl(structs: List[StructInfo], type_aliases: Dict[str, str]) -> str:
    """Generate overloaded SetParamsMemberByTag function declarations."""
    output = []

    output.append("    // Overloaded SetParamsMemberByTag for each unique parameter type")
    output.append("    // These are non-template functions, reducing binary bloat")
    output.append("    // Generated from FOR_EACH_PARAM_TYPE X-Macro")

    # Collect unique field types from all structs
    # For array elements, use array_accessor_type if specified
    unique_types = set()
    for struct in structs:
        for field in struct.fields:
            if field.prop_attributes:
                for prop_attr in field.prop_attributes:
                    if prop_attr.array_accessor_length is not None:
                        # This is an array accessor field
                        if prop_attr.array_accessor_type:
                            # Use the specified array_accessor_type
                            unique_types.add(prop_attr.array_accessor_type)
                        else:
                            # Fallback to the field type (array type)
                            unique_types.add(field.type)
                    else:
                        # Regular field
                        unique_types.add(field.type)
            else:
                # No prop_attributes: regular field
                unique_types.add(field.type)

    # Normalize types using type aliases
    normalized_types = set()
    for type_str in unique_types:
        normalized_types.add(normalize_type(type_str, type_aliases))

    sorted_types = sorted(normalized_types)

    for field_type in sorted_types:
        output.append(f"    static void SetParamsMemberByTag(const std::shared_ptr<GEFilterParams>& params,")
        output.append(f"                                     GEParamsMemberTag tag, const {field_type}& value);")

    output.append("")

    return '\n'.join(output)


def generate_dispatch_filter_type(structs: List[StructInfo]) -> str:
    """Generate DispatchGEFilterType high-order template function."""
    output = []

    output.append("// High-order template function to dispatch based on GEFilterType")
    output.append("// Func should be a template callable: template<typename ParamsType, typename... Args> struct Func")
    output.append("// Func must have a static void Invoke(Args...) method")
    output.append("template<template<typename, typename...> typename Func, typename... Args>")
    output.append("void DispatchGEFilterType(GEFilterType filterType, Args&&... args)")
    output.append("{")
    output.append("    switch (filterType) {")

    output.append("// Helper macro for FilterType dispatch")
    output.append("#define GE_DISPATCH_CASE_TYPE(FilterType, Struct) \\")
    output.append("    case GEFilterType::FilterType: \\")
    output.append("        Func<Struct, Args...>::Invoke(std::forward<Args>(args)...); \\")
    output.append("        break;")
    output.append("")

    for struct in structs:
        enum_type = struct.enum_type
        struct_name = struct.name
        output.append(f"        GE_DISPATCH_CASE_TYPE({enum_type}, {struct_name})")

    output.append("        default:")
    output.append("            break;")
    output.append("    }")
    output.append("}")
    output.append("")
    output.append("#undef GE_DISPATCH_CASE_TYPE")
    output.append("")

    return '\n'.join(output)


def generate_string_to_enum_mapping_decl() -> str:
    """Generate GEParamsMemberTagFromString() declaration."""
    output = []

    output.append("// String to enum mapping")
    output.append("// Note: Strings are sourced from GEParamsFieldAccessor<Tag>::name for single source of truth")
    output.append("//       Aliases from [[ge::prop_alias]] are also included")
    output.append("GEParamsMemberTag GEParamsMemberTagFromString(const std::string& str);")
    output.append("")

    return '\n'.join(output)


def generate_string_to_enum_mapping_impl(structs: List[StructInfo]) -> str:
    """Generate GEParamsMemberTagFromString() implementation."""
    output = []

    # Collect all string-to-tag mappings, including aliases
    string_to_tags: Dict[str, List[Tuple[str, str]]] = {}
    for struct in structs:
        for field in struct.fields:
            for tag_name, prop_name, is_array_elem, array_idx in iterate_field_tags(struct, field):
                # Add primary prop name
                if prop_name not in string_to_tags:
                    string_to_tags[prop_name] = []
                string_to_tags[prop_name].append((struct.name, tag_name))

                # Add alias if (for first prop attribute)
                if field.prop_attributes and not is_array_elem:
                    prop_attr = field.prop_attributes[0]  # Get first prop attribute
                    if prop_attr.alias:
                        if prop_attr.alias not in string_to_tags:
                            string_to_tags[prop_attr.alias] = []
                        string_to_tags[prop_attr.alias].append((struct.name, tag_name))

    # Check for collisions
    collisions = []
    for prop_name, tags in string_to_tags.items():
        if len(tags) > 1:
            collisions.append((prop_name, tags))

    if collisions:
        error_lines = ["Error: String collision detected in GEParamsMemberTagFromString mapping:"]
        for prop_name, tags in collisions:
            error_lines.append(f"\n  String '{prop_name}' is used by multiple fields:")
            for struct_name, tag_name in tags:
                error_lines.append(f"    - {struct_name}::{tag_name}")
        raise RuntimeError("\n".join(error_lines))

    output.append("GEParamsMemberTag GEParamsMemberTagFromString(const std::string& str)")
    output.append("{")
    output.append("    static const std::unordered_map<std::string, GEParamsMemberTag> map = {")

    # Helper macro for reducing repetition - uses GEParamsFieldAccessor::name
    output.append("#define GE_STRING_TO_TAG_ENTRY(Tag) \\")
    output.append("    { GEParamsFieldAccessor<GEParamsMemberTag::Tag>::name, GEParamsMemberTag::Tag }")
    output.append("")

    # Helper macro for alias entries
    output.append("#define GE_STRING_TO_TAG_ALIAS(Tag, Alias) \\")
    output.append("    { #Alias, GEParamsMemberTag::Tag }")
    output.append("")

    for struct in structs:
        for field in struct.fields:
            for tag_name, prop_name, is_array_elem, array_idx in iterate_field_tags(struct, field):
                output.append(f"        GE_STRING_TO_TAG_ENTRY({tag_name}),")

                # Add alias entry if present (for the first prop attribute)
                if field.prop_attributes and not is_array_elem:
                    prop_attr = field.prop_attributes[0]
                    if prop_attr.alias:
                        output.append(f"        GE_STRING_TO_TAG_ALIAS({tag_name}, {prop_attr.alias}),")

    output.append("    };")
    output.append("")
    output.append("#undef GE_STRING_TO_TAG_ENTRY")
    output.append("#undef GE_STRING_TO_TAG_ALIAS")
    output.append("")
    output.append("    auto it = map.find(str);")
    output.append("    if (it != map.end()) {")
    output.append("        return it->second;")
    output.append("    }")
    output.append("    return GEParamsMemberTag::INVALID;")
    output.append("}")
    output.append("")

    return '\n'.join(output)

def generate_params_builder_decl() -> str:
    """Generate GEParamsBuilder helper class declaration."""
    output = []

    output.append("class GEParamsBuilder {")
    output.append("public:")
    output.append("    static std::shared_ptr<GEFilterParams> Build(GEFilterType filterType);")
    output.append("};")
    output.append("")

    return '\n'.join(output)


def generate_params_builder_impl(structs: List[StructInfo]) -> str:
    """Generate GEParamsBuilder::Build() implementation."""
    output = []

    output.append("std::shared_ptr<GEFilterParams> GEParamsBuilder::Build(GEFilterType filterType)")
    output.append("{")
    output.append("    switch (filterType) {")
    output.append("#define GE_BUILD_PARAMS_CASE(EnumType, Struct) \\")
    output.append("    case GEFilterType::EnumType: \\")
    output.append("        return GEFilterParams::Box(Struct{});")
    output.append("")

    for struct in structs:
        enum_type = struct.enum_type
        struct_name = struct.name
        output.append(f"        GE_BUILD_PARAMS_CASE({enum_type}, {struct_name})")

    output.append("        default:")
    output.append("            return nullptr;")
    output.append("        }")
    output.append("}")
    output.append("")
    output.append("#undef GE_BUILD_PARAMS_CASE")
    output.append("")

    return '\n'.join(output)

def generate_type_xmacro(structs: List[StructInfo], type_aliases: Dict[str, str]) -> str:
    """Generate X-Macro listing all unique member variable types."""
    output = []

    unique_types = set()
    for struct in structs:
        for field in struct.fields:
            unique_types.add(field.type)

    # Normalize types using type aliases
    normalized_types = set()
    for type_str in unique_types:
        normalized_types.add(normalize_type(type_str, type_aliases))

    sorted_types = sorted(normalized_types)

    output.append("// X-Macro listing all unique parameter member types")
    output.append("// Usage: #define X(Type) <your code>; FOR_EACH_PARAM_TYPE(X); #undef X")
    output.append("#define FOR_EACH_PARAM_TYPE(X) \\")

    for i, type_name in enumerate(sorted_types):
        if i < len(sorted_types) - 1:
            output.append(f"    X({type_name}) \\")
        else:
            output.append(f"    X({type_name})")

    output.append("")
    output.append("")

    return '\n'.join(output)


def _infer_numeric_type(value_str: str) -> str:
    """Infer numeric type from a string value.
    
    Returns 'float' if the value contains a decimal point or 'f' suffix, otherwise 'int'.
    """
    value = value_str.strip()
    if '.' in value or value.endswith('f') or value.endswith('F'):
        return 'float'
    return 'int'


def generate_constraint_metadata(field_info: FieldInfo, tag: str) -> str:
    """Generate constraint metadata for a field with range attribute."""
    range_attr = field_info.range_attr

    if not range_attr:
        return ""

    field_type = field_info.type
    output = []

    if range_attr.min_value is not None and range_attr.max_value is not None:
        output.append(f"GE_PARAMS_CONSTRAINT_RANGE({tag}, {field_type}, {range_attr.min_value}, {range_attr.max_value})")

    elif range_attr.min_components is not None and range_attr.max_components is not None:
        mins = range_attr.min_components
        maxs = range_attr.max_components
        component_type = _infer_numeric_type(mins[0])
        mins_str = ', '.join(mins)
        maxs_str = ', '.join(maxs)
        output.append(f"GE_PARAMS_CONSTRAINT_COMPONENTS({tag}, {component_type}, {len(mins)}, ESCAPE({{{mins_str}}}), ESCAPE({{{maxs_str}}}))")

    elif range_attr.min_components is not None:
        mins = range_attr.min_components
        component_type = _infer_numeric_type(mins[0])
        mins_str = ', '.join(mins)
        output.append(f"GE_PARAMS_CONSTRAINT_COMPONENTS_MIN({tag}, {component_type}, {len(mins)}, ESCAPE({{{mins_str}}}))")

    elif range_attr.max_components is not None:
        maxs = range_attr.max_components
        component_type = _infer_numeric_type(maxs[0])
        maxs_str = ', '.join(maxs)
        output.append(f"GE_PARAMS_CONSTRAINT_COMPONENTS_MAX({tag}, {component_type}, {len(maxs)}, ESCAPE({{{maxs_str}}}))")

    elif range_attr.min_value is not None:
        output.append(f"GE_PARAMS_CONSTRAINT_MIN({tag}, {field_type}, {range_attr.min_value})")

    elif range_attr.max_value is not None:
        output.append(f"GE_PARAMS_CONSTRAINT_MAX({tag}, {field_type}, {range_attr.max_value})")

    return '\n'.join(output)


def generate_transform_helper(structs: List[StructInfo]) -> str:
    """Generate dispatch helper for runtime tag resolution."""
    output = []

    output.append("// Dispatch helper for runtime tag resolution")
    output.append("template<typename T>")
    output.append("struct GEParamsTransformHelper {")
    output.append("    static T Transform(GEParamsMemberTag tag, T value) {")
    output.append("        switch (tag) {")

    for struct in structs:
        for field in struct.fields:
            if field.range_attr:
                for tag_name, _, _, _ in iterate_field_tags(struct, field):
                    output.append(f"            case GEParamsMemberTag::{tag_name}:")
                    output.append(f"                return GEParamsValueTransformer<GEParamsMemberTag::{tag_name}, T>::Transform(value);")

    output.append("            default:")
    output.append("                return value;")
    output.append("        }")
    output.append("    }")
    output.append("};")
    output.append("")

    return '\n'.join(output)


def generate_header(structs: List[StructInfo], type_aliases: Dict[str, str]) -> str:
    """Generate the complete header file."""
    output = []

    output.append(COPYRIGHT_HEADER)
    output.append("")
    output.append("#ifndef GRAPHICS_EFFECT_GE_PARAMS_REFLECTION_V2_H")
    output.append("#define GRAPHICS_EFFECT_GE_PARAMS_REFLECTION_V2_H")
    output.append("")
    output.append("#include <optional>")
    output.append("#include <string>")
    output.append("#include <string_view>")
    output.append("#include <type_traits>")
    output.append("#include \"ge_effects_params.h\"")
    output.append("#include \"ge_filter_params.h\"")
    output.append("#include \"ge_value_transformer.h\"")
    output.append("")

    output.append("namespace OHOS {")
    output.append("namespace Rosen {")
    output.append("namespace Drawing {")
    output.append("")

    output.append(generate_type_xmacro(structs, type_aliases))

    # Generate member enums and tag ranges
    enum_code, struct_tag_ranges = generate_member_enums(structs)
    output.append(enum_code)

    # Generate constraint metadata macros
    output.append("")
    output.append("// Helper macro to escape commas in macro arguments")
    output.append("#define ESCAPE(...) __VA_ARGS__")
    output.append("")
    output.append("// Constraint Metadata Macros")
    output.append("#define GE_PARAMS_CONSTRAINT_RANGE(Tag, Type, Min, Max) \\")
    output.append("    template<> \\")
    output.append("    struct GEParamsConstraintInfo<GEParamsMemberTag::Tag> { \\")
    output.append("        static constexpr bool HAS_RANGE = true; \\")
    output.append("        static constexpr bool COMPONENT_WISE = false; \\")
    output.append("        static constexpr bool HAS_MIN = true; \\")
    output.append("        static constexpr bool HAS_MAX = true; \\")
    output.append("        static constexpr Type MIN = Min; \\")
    output.append("        static constexpr Type MAX = Max; \\")
    output.append("    };")
    output.append("")
    output.append("#define GE_PARAMS_CONSTRAINT_COMPONENTS(Tag, Type, Count, Mins, Maxs) \\")
    output.append("    template<> \\")
    output.append("    struct GEParamsConstraintInfo<GEParamsMemberTag::Tag> { \\")
    output.append("        static constexpr bool HAS_RANGE = true; \\")
    output.append("        static constexpr bool COMPONENT_WISE = true; \\")
    output.append("        static constexpr bool HAS_MIN = true; \\")
    output.append("        static constexpr bool HAS_MAX = true; \\")
    output.append("        static constexpr size_t COMPONENT_COUNT = Count; \\")
    output.append("        static constexpr Type MIN_COMPONENTS[] = Mins; \\")
    output.append("        static constexpr Type MAX_COMPONENTS[] = Maxs; \\")
    output.append("    };")
    output.append("")
    output.append("#define GE_PARAMS_CONSTRAINT_COMPONENTS_MIN(Tag, Type, Count, Mins) \\")
    output.append("    template<> \\")
    output.append("    struct GEParamsConstraintInfo<GEParamsMemberTag::Tag> { \\")
    output.append("        static constexpr bool HAS_RANGE = true; \\")
    output.append("        static constexpr bool COMPONENT_WISE = true; \\")
    output.append("        static constexpr bool HAS_MIN = true; \\")
    output.append("        static constexpr size_t COMPONENT_COUNT = Count; \\")
    output.append("        static constexpr Type MIN_COMPONENTS[] = Mins; \\")
    output.append("    };")
    output.append("")
    output.append("#define GE_PARAMS_CONSTRAINT_COMPONENTS_MAX(Tag, Type, Count, Maxs) \\")
    output.append("    template<> \\")
    output.append("    struct GEParamsConstraintInfo<GEParamsMemberTag::Tag> { \\")
    output.append("        static constexpr bool HAS_RANGE = true; \\")
    output.append("        static constexpr bool HAS_MAX = true; \\")
    output.append("        static constexpr size_t COMPONENT_COUNT = Count; \\")
    output.append("        static constexpr Type MAX_COMPONENTS[] = Maxs; \\")
    output.append("    };")
    output.append("")
    output.append("#define GE_PARAMS_CONSTRAINT_MIN(Tag, Type, Min) \\")
    output.append("    template<> \\")
    output.append("    struct GEParamsConstraintInfo<GEParamsMemberTag::Tag> { \\")
    output.append("        static constexpr bool HAS_RANGE = true; \\")
    output.append("        static constexpr bool HAS_MIN = true; \\")
    output.append("        static constexpr Type MIN = Min; \\")
    output.append("    };")
    output.append("")
    output.append("#define GE_PARAMS_CONSTRAINT_MAX(Tag, Type, Max) \\")
    output.append("    template<> \\")
    output.append("    struct GEParamsConstraintInfo<GEParamsMemberTag::Tag> { \\")
    output.append("        static constexpr bool HAS_RANGE = true; \\")
    output.append("        static constexpr bool HAS_MAX = true; \\")
    output.append("        static constexpr Type MAX = Max; \\")
    output.append("    };")
    output.append("")

    # Generate constraint metadata for constrained fields
    for struct in structs:
        for field in struct.fields:
            for tag_name, _, _, _ in iterate_field_tags(struct, field):
                metadata = generate_constraint_metadata(field, tag_name)
                if metadata:
                    output.append(metadata)

    # Undefine constraint metadata macros
    output.append("#undef GE_PARAMS_CONSTRAINT_RANGE")
    output.append("#undef GE_PARAMS_CONSTRAINT_COMPONENTS")
    output.append("#undef GE_PARAMS_CONSTRAINT_COMPONENTS_MIN")
    output.append("#undef GE_PARAMS_CONSTRAINT_COMPONENTS_MAX")
    output.append("#undef GE_PARAMS_CONSTRAINT_MIN")
    output.append("#undef GE_PARAMS_CONSTRAINT_MAX")
    output.append("")

    # Generate GEFilterParamsTypeInfo specializations
    output.append(generate_filter_params_type_info(structs))
    output.append(generate_params_builder_decl())

    # Generate type traits
    output.append(generate_type_traits(structs))

    # Generate GEParamsMemberHelper declaration (includes SetParamsMemberByTag template)
    output.append(generate_struct_tag_ranges_decl(structs, type_aliases))

    # Generate string-to-enum mapping declaration
    output.append(generate_string_to_enum_mapping_decl())

    output.append("} // namespace Drawing")
    output.append("} // namespace Rosen")
    output.append("} // namespace OHOS")
    output.append("")
    output.append("#endif // GRAPHICS_EFFECT_GE_PARAMS_REFLECTION_V2_H")

    return '\n'.join(output)


def generate_cpp(structs: List[StructInfo], type_aliases: Dict[str, str]) -> str:
    """Generate the complete cpp file."""
    output = []

    output.append(COPYRIGHT_HEADER)
    output.append("")
    output.append("#include \"ge_params_reflection_v2.h\"")
    output.append("#include <unordered_map>")
    output.append("")

    output.append("namespace OHOS {")
    output.append("namespace Rosen {")
    output.append("namespace Drawing {")
    output.append("")

    # Generate GEParamsBuilder::Build() implementation
    output.append(generate_params_builder_impl(structs))

    # Generate GEParamsMemberHelper::GetParamsMemberTagRange() implementation
    output.append(generate_struct_tag_ranges_impl(structs))

    # Generate GEParamsMemberHelper::GetFilterTypeFromTag() implementation
    output.append(generate_get_filter_type_from_tag_impl(structs))

    # Generate GEParamsMemberTagFromString() implementation
    output.append(generate_string_to_enum_mapping_impl(structs))

    # Generate overloaded SetParamsMemberByTag implementations
    output.append(generate_set_params_member_overloads_impl(structs, type_aliases))

    output.append("} // namespace Drawing")
    output.append("} // namespace Rosen")
    output.append("} // namespace OHOS")
    output.append("")

    return '\n'.join(output)


def main():
    """Main generation function."""
    parser = argparse.ArgumentParser(
        description='Generate C++ static reflection metadata from .params files',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python generate_reflection_metadata_v2.py
  python generate_reflection_metadata_v2.py --params-dirs custom/filter custom/maz --output-file custom/reflection.h
        """
    )

    parser.add_argument(
        '--params-dirs',
        type=str,
        nargs='+',
        default=None,
        help='Directories containing .params files (default: include/effect/filter include/effect/mask include/effect/shader include/effect/shape)'
    )

    parser.add_argument(
        '--output-file',
        type=str,
        default=None,
        help='Output header file path (default: include/effect/ge_params_reflection_v2.h)'
    )

    parser.add_argument(
        '--output-cpp-file',
        type=str,
        default=None,
        help='Output cpp file path (default: src/effect/ge_params_reflection_v2.cpp)'
    )

    parser.add_argument(
        '--config-file',
        type=str,
        default=None,
        help='Config file path (default: tool/effectgen/config.json)'
    )

    args = parser.parse_args()

    root_dir = Path(__file__).parent.parent.parent

    if args.params_dirs:
        params_dirs = [Path(d) for d in args.params_dirs]
    else:
        params_dirs = [
            root_dir / "include" / "effect" / "filter",
            root_dir / "include" / "effect" / "mask",
            root_dir / "include" / "effect" / "shader",
            root_dir / "include" / "effect" / "shape",
        ]
    output_file = Path(args.output_file) if args.output_file else root_dir / "include" / "effect" / "ge_params_reflection_v2.h"
    output_cpp_file = Path(args.output_cpp_file) if args.output_cpp_file else root_dir / "src" / "effect" / "ge_params_reflection_v2.cpp"
    config_file = Path(args.config_file) if args.config_file else Path(__file__).parent / "config.json"

    # Load type aliases from config
    type_aliases = load_config(config_file)
    print(f"Loaded {len(type_aliases)} type aliases from {config_file}")

    params_files = []
    for params_dir in params_dirs:
        params_files.extend(list(params_dir.glob("*.params")))
    params_files.sort(key=lambda p: p.name)

    if not params_files:
        print(f"No .params files found in {params_dirs}", file=sys.stderr)
        return 1

    print(f"Found {len(params_files)} .params files in {params_dirs}")

    structs = []
    for params_file in params_files:
        struct_info = parse_def_file(params_file)
        if struct_info:
            structs.append(struct_info)
            print(f"  Parsed: {struct_info.name}")
        else:
            print(f"  Warning: Failed to parse {params_file.name}", file=sys.stderr)

    if not structs:
        print("No valid structs found!", file=sys.stderr)
        return 1

    print(f"Parsed {len(structs)} structs with {sum(len(s.fields) for s in structs)} total fields")

    # Generate header file
    print(f"Generating {output_file.name}...")
    header_content = generate_header(structs, type_aliases)

    # Ensure output directory exists
    output_file.parent.mkdir(parents=True, exist_ok=True)

    # Write to file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(header_content)

    print(f"Generated {output_file}")
    print(f"  - {len(structs)} parameter types")
    print(f"  - {sum(len(s.fields) for s in structs)} total fields")

    # Generate cpp file
    print(f"Generating {output_cpp_file.name}...")
    cpp_content = generate_cpp(structs, type_aliases)

    # Ensure output directory exists
    output_cpp_file.parent.mkdir(parents=True, exist_ok=True)

    # Write to file
    with open(output_cpp_file, 'w', encoding='utf-8') as f:
        f.write(cpp_content)

    print(f"Generated {output_cpp_file}")
    return 0


if __name__ == '__main__':
    exit(main())
