#!/usr/bin/env python3
"""
Generate C++ static reflection metadata from .def files (Improved Version).

This script provides a best-in-effort C++ parser with:
- Proper tokenization (handling comments, strings, char literals, etc.)
- Flexible struct parsing
- C#/Rust-style attribute parsing (e.g., [[ge::params(type=AIBAR, name="AIBAR")]])
- Extensible design for future enhancements
"""

import sys
import argparse
from pathlib import Path
from typing import Dict, List, Tuple, Optional

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

# Import parser modules
from tool.effectgen.cpp_tokenizer import CppTokenizer
from tool.effectgen.cpp_parser import CppParser, StructInfo, FieldInfo

# Copyright header for generated files
COPYRIGHT_HEADER = """/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// AUTO GENERATED BY tools/generate_reflection_metadata_v2.py
// DO NOT EDIT MANUALLY
"""


def parse_def_file(file_path: Path, report_errors: bool = True) -> Optional[StructInfo]:
    """Parse a .def file and extract struct information."""
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Tokenize
    tokenizer = CppTokenizer(content)
    tokens = tokenizer.tokenize()

    # Parse
    parser = CppParser(tokens, str(file_path))
    structs = parser.parse()

    # Report errors if requested
    if report_errors and parser.errors:
        for error in parser.errors:
            print(f"  {error}", file=sys.stderr)

    # Return the first (and typically only) struct
    if structs:
        return structs[0]
    return None


def to_upper_case(name: str) -> str:
    """Convert camelCase or snake_case to UPPER_CASE."""
    if name.endswith('_'):
        name = name[:-1]
    result = []
    for c in name:
        if c.isupper():
            if result:
                result.append('_')
            result.append(c)
        else:
            result.append(c.upper())
    return ''.join(result)


def to_pascal_case(name: str) -> str:
    """Convert snake_case or camelCase to PascalCase.

    Examples:
        propName -> PropName
        prop_name -> PropName
        _propName -> PropName (strip leading underscore)
    """
    # Remove trailing underscore
    if name.endswith('_'):
        name = name[:-1]
    # Remove leading underscore
    if name.startswith('_'):
        name = name[1:]

    if not name:
        return name

    # Convert to PascalCase
    result = []
    capitalize_next = True
    for c in name:
        if c == '_':
            capitalize_next = True
        elif capitalize_next:
            result.append(c.upper())
            capitalize_next = False
        else:
            result.append(c)
    return ''.join(result)


def to_member_tag_name(enum_type: str, field_name: str, index: Optional[int] = None) -> str:
    """Generate GEParamsMemberTag enum name.

    Args:
        enum_type: The enum type (e.g., BEZIER_WARP)
        field_name: The field name (e.g., destinationPatch)
        index: Optional index for array accessor fields (e.g., 0 for destinationPatch[0])
    """
    field_upper = to_upper_case(field_name)
    if index is not None:
        return f"{enum_type}_{field_upper}{index}"
    return f"{enum_type}_{field_upper}"


def get_effective_prop_name(field: FieldInfo, filter_name: str, index: Optional[int] = None) -> str:
    """Get the effective property name for a field.

    Args:
        field: The field info
        filter_name: The filter name
        index: Optional index for array accessor fields

    Note:
        Uses PascalCase as default for fields without explicit [[ge::prop]].
        Fields that need UPPER_CASE naming should use explicit [[ge::prop("UPPER_CASE_NAME")]].
    """
    if field.prop_name:
        if index is not None:
            return f"{field.prop_name}{index}"
        return field.prop_name
    # Use PascalCase as default for fields without explicit prop
    base_name = to_pascal_case(field.name)
    if index is not None:
        return f"{filter_name}_{base_name}{index}"
    return f"{filter_name}_{base_name}"


def iterate_field_tags(struct: StructInfo, field: FieldInfo):
    """Helper to iterate over all tags for a field.

    Yields tuples of (tag_name, prop_name, is_array_element, array_index).
    For array elements, array_index is the element index.
    For whole-field accessors, is_array_element is False and array_index is None.
    """
    enum_type = struct.enum_type

    if field.prop_attributes:
        for prop_attr in field.prop_attributes:
            if prop_attr.array_accessor_length is not None:
                # Generate tags for each array element
                for i in range(prop_attr.array_accessor_length):
                    tag_name = to_member_tag_name(enum_type, field.name, i)
                    prop_name = f"{prop_attr.name}{i}"
                    yield (tag_name, prop_name, True, i)
            else:
                # Single tag for whole-field accessor
                tag_name = to_member_tag_name(enum_type, field.name)
                prop_name = prop_attr.name
                yield (tag_name, prop_name, False, None)
    else:
        # No prop_attributes: single tag for field
        tag_name = to_member_tag_name(enum_type, field.name)
        prop_name = get_effective_prop_name(field, struct.filter_name)
        yield (tag_name, prop_name, False, None)


def generate_member_enums(structs: List[StructInfo]) -> Tuple[str, Dict[str, Tuple[int, int, str]]]:
    """Generate GEParamsMemberTag enum."""
    output = []

    # Generate member tag enum
    output.append("enum class GEParamsMemberTag : uint32_t {")
    output.append("    INVALID = 0,")

    tag_count = 1
    struct_tag_ranges = {}
    for struct in structs:
        first_tag = tag_count
        enum_start = struct.enum_type

        for field in struct.fields:
            for tag_name, _, _, _ in iterate_field_tags(struct, field):
                output.append(f"    {tag_name},")
                tag_count += 1

        last_tag = tag_count - 1
        struct_tag_ranges[struct.name] = (first_tag, last_tag, enum_start)

    output.append("};")
    output.append("")
    return '\n'.join(output), struct_tag_ranges


def generate_struct_tag_ranges(structs: List[StructInfo], struct_tag_ranges: Dict[str, Tuple[int, int, str]]) -> str:
    """Generate GEParamsMemberHelper static class with GetParamsMemberTagRange."""
    output = []

    output.append("")
    output.append("// FilterType to TagRange mapping")
    output.append("struct GEParamsMemberTagRange {")
    output.append("    GEParamsMemberTag RangeStart;")
    output.append("    GEParamsMemberTag RangeEnd;")
    output.append("};")
    output.append("")

    output.append("// Static helper class for params member tag operations")
    output.append("class GEParamsMemberHelper {")
    output.append("public:")
    output.append("    // Get tag range for a given FilterType (using switch for performance)")
    output.append("    static std::optional<GEParamsMemberTagRange> GetParamsMemberTagRange(GEFilterType filterType)")
    output.append("    {")
    output.append("        switch (filterType) {")

    # Generate macro for reducing repetition
    output.append("#define GE_GET_TAG_RANGE_CASE(EnumType, FirstTag, LastTag) \\")
    output.append("    case GEFilterType::EnumType: \\")
    output.append("        return {{ GEParamsMemberTag::FirstTag, GEParamsMemberTag::LastTag }};")
    output.append("")

    for struct in structs:
        enum_type = struct.enum_type
        # Get first and last tag names using helper
        first_tag = None
        last_tag = None
        for field in struct.fields:
            for tag_name, _, _, _ in iterate_field_tags(struct, field):
                if first_tag is None:
                    first_tag = tag_name
                last_tag = tag_name

        if first_tag and last_tag:
            output.append(f"        GE_GET_TAG_RANGE_CASE({enum_type}, {first_tag}, {last_tag})")

    output.append("        default:")
    output.append("            return std::nullopt;")
    output.append("        }")
    output.append("    }")

    output.append("")
    output.append("    // Set params member by tag (dispatch based on tag value)")
    output.append("    template<typename ParamsType, typename T>")
    output.append("    static void SetParamsMemberByTag(ParamsType& params, GEParamsMemberTag tag, const T& value)")
    output.append("    {")
    output.append("        switch (tag) {")

    output.append("#define GE_SET_MEMBER_CASE(Tag) \\")
    output.append("    case GEParamsMemberTag::Tag: \\")
    output.append("        if constexpr (std::is_same_v<ParamsType, GEParamsFieldAccessor<GEParamsMemberTag::Tag>::ParamsType>) {{ \\")
    output.append("            GEParamsFieldAccessor<GEParamsMemberTag::Tag>::Set(params, value); \\")
    output.append("        }} \\")
    output.append("        break;")
    output.append("")

    for struct in structs:
        for field in struct.fields:
            for tag_name, _, _, _ in iterate_field_tags(struct, field):
                output.append(f"        GE_SET_MEMBER_CASE({tag_name})")

    output.append("        default:")
    output.append("            break;")
    output.append("        }")
    output.append("    }")

    output.append("")
    output.append("#undef GE_GET_TAG_RANGE_CASE")
    output.append("#undef GE_SET_MEMBER_CASE")
    output.append("};")
    output.append("")

    return '\n'.join(output)


def generate_filter_params_type_info(structs: List[StructInfo]) -> str:
    """Generate GEFilterParamsTypeInfo template specializations."""
    output = []

    output.append("// GEFilterParamsTypeInfo template specializations")
    output.append("// Provides FilterType ID and FilterName for each params type")
    output.append("template<typename T>")
    output.append("struct GEFilterParamsTypeInfo {")
    output.append("    using Self = T;")
    output.append("    static constexpr GEFilterType ID = GEFilterType::NONE;")
    output.append("    static constexpr std::string_view FilterName = \"\";")
    output.append("};")
    output.append("")

    output.append("// Helper macro for GEParamsTypeInfo specializations")
    output.append("#define GE_PARAMS_TYPE_INFO(Struct, FilterTypeEnum, FilterNameStr) \\")
    output.append("    template<> \\")
    output.append("    struct GEFilterParamsTypeInfo<Struct> { \\")
    output.append("        using Self = Struct; \\")
    output.append("        static constexpr GEFilterType ID = GEFilterType::FilterTypeEnum; \\")
    output.append("        static constexpr std::string_view FilterName = #FilterNameStr; \\")
    output.append("    };")
    output.append("")

    for struct in structs:
        enum_type = struct.enum_type
        struct_name = struct.name
        filter_name = struct.filter_name
        output.append(f"GE_PARAMS_TYPE_INFO({struct_name}, {enum_type}, {filter_name})")

    output.append("")
    output.append("#undef GE_PARAMS_TYPE_INFO")
    output.append("")

    return '\n'.join(output)


def generate_type_traits(structs: List[StructInfo]) -> str:
    """Generate type traits for parameter structs."""
    output = []

    output.append("// Type traits for accessing struct fields")
    output.append("template<GEParamsMemberTag Tag>")
    output.append("struct GEParamsFieldAccessor;")
    output.append("")

    output.append("// Helper macro for generating field accessors")
    output.append("#define GE_PARAMS_FIELD_ACCESSOR(Struct, Field, Tag, PropName) \\")
    output.append("    template<> \\")
    output.append("    struct GEParamsFieldAccessor<GEParamsMemberTag::Tag> { \\")
    output.append("        using ParamsType = Struct; \\")
    output.append("        using FieldType = decltype(Struct::Field); \\")
    output.append("        static constexpr const char name[] = #PropName; \\")
    output.append("        static FieldType& Get(ParamsType& params) { return params.Field; } \\")
    output.append("        static const FieldType& Get(const ParamsType& params) { return params.Field; } \\")
    output.append("        static void Set(ParamsType& params, const FieldType& value) { params.Field = value; } \\")
    output.append("    };")
    output.append("")

    # Helper macro for array element accessors
    output.append("// Helper macro for generating array element field accessors")
    output.append("#define GE_PARAMS_ARRAY_ELEMENT_ACCESSOR(Struct, Field, Index, Tag, PropName) \\")
    output.append("    template<> \\")
    output.append("    struct GEParamsFieldAccessor<GEParamsMemberTag::Tag> { \\")
    output.append("        using ParamsType = Struct; \\")
    output.append("        using FieldType = typename decltype(Struct::Field)::value_type; \\")
    output.append("        static constexpr const char* name = #PropName; \\")
    output.append("        static FieldType& Get(ParamsType& params) { return params.Field[Index]; } \\")
    output.append("        static const FieldType& Get(const ParamsType& params) { return params.Field[Index]; } \\")
    output.append("        static void Set(ParamsType& params, const FieldType& value) { params.Field[Index] = value; } \\")
    output.append("    };")
    output.append("")

    for struct in structs:
        for field in struct.fields:
            for tag_name, prop_name, is_array_elem, array_idx in iterate_field_tags(struct, field):
                if is_array_elem:
                    output.append(f"GE_PARAMS_ARRAY_ELEMENT_ACCESSOR({struct.name}, {field.name}, {array_idx}, {tag_name}, {prop_name})")
                else:
                    output.append(f"GE_PARAMS_FIELD_ACCESSOR({struct.name}, {field.name}, {tag_name}, {prop_name})")

    output.append("")
    output.append("#undef GE_PARAMS_FIELD_ACCESSOR")
    output.append("#undef GE_PARAMS_ARRAY_ELEMENT_ACCESSOR")
    output.append("")

    return '\n'.join(output)


def generate_dispatch_filter_type(structs: List[StructInfo]) -> str:
    """Generate DispatchGEFilterType high-order template function."""
    output = []

    output.append("// High-order template function to dispatch based on GEFilterType")
    output.append("// Func should be a template callable: template<typename ParamsType, typename... Args> struct Func")
    output.append("// Func must have a static void Invoke(Args...) method")
    output.append("template<template<typename, typename...> typename Func, typename... Args>")
    output.append("void DispatchGEFilterType(GEFilterType filterType, Args&&... args)")
    output.append("{")
    output.append("    switch (filterType) {")

    output.append("// Helper macro for FilterType dispatch")
    output.append("#define GE_DISPATCH_CASE_TYPE(FilterType, Struct) \\")
    output.append("    case GEFilterType::FilterType: \\")
    output.append("        Func<Struct, Args...>::Invoke(std::forward<Args>(args)...); \\")
    output.append("        break;")
    output.append("")

    for struct in structs:
        enum_type = struct.enum_type
        struct_name = struct.name
        output.append(f"        GE_DISPATCH_CASE_TYPE({enum_type}, {struct_name})")

    output.append("        default:")
    output.append("            break;")
    output.append("    }")
    output.append("}")
    output.append("")
    output.append("#undef GE_DISPATCH_CASE_TYPE")
    output.append("")

    return '\n'.join(output)


def generate_string_to_enum_mapping(structs: List[StructInfo]) -> str:
    """Generate string-to-enum mapping."""
    output = []

    # Collect all string-to-tag mappings, including aliases
    string_to_tags: Dict[str, List[Tuple[str, str]]] = {}
    for struct in structs:
        for field in struct.fields:
            for tag_name, prop_name, is_array_elem, array_idx in iterate_field_tags(struct, field):
                # Add primary prop name
                if prop_name not in string_to_tags:
                    string_to_tags[prop_name] = []
                string_to_tags[prop_name].append((struct.name, tag_name))

                # Add alias if (for first prop attribute)
                if field.prop_attributes and not is_array_elem:
                    prop_attr = field.prop_attributes[0]  # Get first prop attribute
                    if prop_attr.alias:
                        if prop_attr.alias not in string_to_tags:
                            string_to_tags[prop_attr.alias] = []
                        string_to_tags[prop_attr.alias].append((struct.name, tag_name))

    # Check for collisions
    collisions = []
    for prop_name, tags in string_to_tags.items():
        if len(tags) > 1:
            collisions.append((prop_name, tags))

    if collisions:
        error_lines = ["Error: String collision detected in GEParamsMemberTagFromString mapping:"]
        for prop_name, tags in collisions:
            error_lines.append(f"\n  String '{prop_name}' is used by multiple fields:")
            for struct_name, tag_name in tags:
                error_lines.append(f"    - {struct_name}::{tag_name}")
        raise RuntimeError("\n".join(error_lines))

    output.append("// String to enum mapping")
    output.append("// Note: Strings are sourced from GEParamsFieldAccessor<Tag>::name for single source of truth")
    output.append("//       Aliases from [[ge::prop_alias]] are also included")
    output.append("inline GEParamsMemberTag GEParamsMemberTagFromString(const std::string& str)")
    output.append("{")
    output.append("    static const std::unordered_map<std::string, GEParamsMemberTag> map = {")

    # Helper macro for reducing repetition - uses GEParamsFieldAccessor::name
    output.append("#define GE_STRING_TO_TAG_ENTRY(Tag) \\")
    output.append("    { GEParamsFieldAccessor<GEParamsMemberTag::Tag>::name, GEParamsMemberTag::Tag }")
    output.append("")

    # Helper macro for alias entries
    output.append("#define GE_STRING_TO_TAG_ALIAS(Tag, Alias) \\")
    output.append("    { #Alias, GEParamsMemberTag::Tag }")
    output.append("")

    for struct in structs:
        for field in struct.fields:
            for tag_name, prop_name, is_array_elem, array_idx in iterate_field_tags(struct, field):
                output.append(f"        GE_STRING_TO_TAG_ENTRY({tag_name}),")

                # Add alias entry if present (for the first prop attribute)
                if field.prop_attributes and not is_array_elem:
                    prop_attr = field.prop_attributes[0]
                    if prop_attr.alias:
                        output.append(f"        GE_STRING_TO_TAG_ALIAS({tag_name}, {prop_attr.alias}),")

    output.append("    };")
    output.append("")
    output.append("#undef GE_STRING_TO_TAG_ENTRY")
    output.append("#undef GE_STRING_TO_TAG_ALIAS")
    output.append("")
    output.append("    auto it = map.find(str);")
    output.append("    if (it != map.end()) {")
    output.append("        return it->second;")
    output.append("    }")
    output.append("    return GEParamsMemberTag::INVALID;")
    output.append("}")
    output.append("")

    return '\n'.join(output)


def generate_header(structs: List[StructInfo]) -> str:
    """Generate the complete header file."""
    output = []

    output.append(COPYRIGHT_HEADER)
    output.append("")
    output.append("#ifndef GRAPHICS_EFFECT_GE_PARAMS_REFLECTION_V2_H")
    output.append("#define GRAPHICS_EFFECT_GE_PARAMS_REFLECTION_V2_H")
    output.append("")
    output.append("#include <optional>")
    output.append("#include <string>")
    output.append("#include <string_view>")
    output.append("#include <type_traits>")
    output.append("#include \"ge_effects_params.h\"")
    output.append("")

    output.append("namespace OHOS {")
    output.append("namespace Rosen {")
    output.append("namespace Drawing {")
    output.append("")

    # Generate member enums and tag ranges
    enum_code, struct_tag_ranges = generate_member_enums(structs)
    output.append(enum_code)

    # Generate GEFilterParamsTypeInfo specializations
    output.append(generate_filter_params_type_info(structs))

    # Generate type traits
    output.append(generate_type_traits(structs))

    # Generate GEParamsMemberHelper (includes GetParamsMemberTagRange and SetParamsMemberByTag)
    output.append(generate_struct_tag_ranges(structs, struct_tag_ranges))

    # Generate DispatchGEFilterType (includes macro definition and undef)
    output.append(generate_dispatch_filter_type(structs))

    # Generate string-to-enum mapping
    output.append(generate_string_to_enum_mapping(structs))

    output.append("} // namespace Drawing")
    output.append("} // namespace Rosen")
    output.append("} // namespace OHOS")
    output.append("")
    output.append("#endif // GRAPHICS_EFFECT_GE_PARAMS_REFLECTION_V2_H")

    return '\n'.join(output)


def main():
    """Main generation function."""
    parser = argparse.ArgumentParser(
        description='Generate C++ static reflection metadata from .def files',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python generate_reflection_metadata_v2.py
  python generate_reflection_metadata_v2.py --params-dir custom/params --output-file custom/reflection.h
        """
    )

    parser.add_argument(
        '--params-dir',
        type=str,
        default=None,
        help='Directory containing .def files (default: include/effect/params)'
    )

    parser.add_argument(
        '--output-file',
        type=str,
        default=None,
        help='Output header file path (default: include/effect/ge_params_reflection_v2.h)'
    )

    args = parser.parse_args()

    root_dir = Path(__file__).parent.parent.parent

    # Use command line args or defaults
    params_dir = Path(args.params_dir) if args.params_dir else root_dir / "include" / "effect" / "params"
    output_file = Path(args.output_file) if args.output_file else root_dir / "include" / "effect" / "ge_params_reflection_v2.h"

    # Find all .def files
    def_files = list(params_dir.glob("*.def"))
    def_files.sort()

    if not def_files:
        print(f"No .def files found in {params_dir}", file=sys.stderr)
        return 1

    print(f"Found {len(def_files)} .def files in {params_dir}")

    # Parse all .def files
    structs = []
    for def_file in def_files:
        struct_info = parse_def_file(def_file)
        if struct_info:
            structs.append(struct_info)
            print(f"  Parsed: {struct_info.name}")
        else:
            print(f"  Warning: Failed to parse {def_file.name}", file=sys.stderr)

    if not structs:
        print("No valid structs found!", file=sys.stderr)
        return 1

    print(f"Parsed {len(structs)} structs with {sum(len(s.fields) for s in structs)} total fields")

    # Generate header file
    print(f"Generating {output_file.name}...")
    header_content = generate_header(structs)

    # Ensure output directory exists
    output_file.parent.mkdir(parents=True, exist_ok=True)

    # Write to file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(header_content)

    print(f"Generated {output_file}")
    print(f"  - {len(structs)} parameter types")
    print(f"  - {sum(len(s.fields) for s in structs)} total fields")
    return 0


if __name__ == '__main__':
    exit(main())
