"""HTML template generation for GE shader diagnostics reports and diffs.

All HTML output is self-contained with embedded CSS — no external dependencies.
Uses semantic HTML with <details>/<summary> for expandable source code sections.
"""

import html

CSS = """\
:root {
  --bg: #ffffff;
  --surface: #f6f8fa;
  --border: #d0d7de;
  --text: #1f2328;
  --text-secondary: #656d76;
  --accent: #0969da;
  --green: #1a7f37;
  --green-bg: #dafbe1;
  --green-border: #2da44e;
  --red: #cf222e;
  --red-bg: #ffebe9;
  --red-border: #d1242f;
  --amber: #9a6700;
  --amber-bg: #fff8c5;
  --amber-border: #bf8700;
  --code-bg: #f6f8fa;
}
* { box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Noto Sans, Helvetica, Arial, sans-serif;
  color: var(--text);
  max-width: 1200px;
  margin: 0 auto;
  padding: 24px 32px;
  line-height: 1.6;
}
h1 { border-bottom: 1px solid var(--border); padding-bottom: 12px; margin-bottom: 8px; }
h2 { margin-top: 28px; margin-bottom: 12px; }
.meta { color: var(--text-secondary); font-size: 14px; margin: 4px 0 16px; }
.summary-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
  gap: 12px;
  margin: 16px 0 24px;
}
.card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 12px 16px;
}
.card-label { font-size: 12px; color: var(--text-secondary); margin: 0; text-transform: uppercase; letter-spacing: 0.5px; }
.card-value { font-size: 22px; font-weight: 600; margin: 4px 0 0; }
.card-value.green { color: var(--green); }
.card-value.red { color: var(--red); }
.card-value.amber { color: var(--amber); }
table { width: 100%; border-collapse: collapse; margin: 12px 0 20px; }
th, td { padding: 8px 12px; border-bottom: 1px solid var(--border); text-align: left; }
th { background: var(--surface); font-weight: 600; font-size: 13px; color: var(--text-secondary); }
.hash { font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace; font-size: 12px; }
.source-code {
  background: var(--code-bg);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 12px 16px;
  font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace;
  font-size: 13px;
  line-height: 1.5;
  white-space: pre;
  overflow-x: auto;
  max-height: 400px;
  overflow-y: auto;
}
details { margin: 6px 0; }
summary { cursor: pointer; color: var(--accent); font-weight: 500; font-size: 14px; }
summary:hover { text-decoration: underline; }
.section { border-radius: 6px; padding: 16px 20px; margin: 12px 0; }
.section-added { background: var(--green-bg); border-left: 4px solid var(--green-border); }
.section-removed { background: var(--red-bg); border-left: 4px solid var(--red-border); }
.section-changed { background: var(--amber-bg); border-left: 4px solid var(--amber-border); }
.section h3 { margin: 0 0 8px; font-size: 16px; }
.site-left { color: var(--red); font-weight: 500; }
.site-right { color: var(--green); font-weight: 500; }
.call-site { font-family: 'SFMono-Regular', Consolas, monospace; font-size: 13px; }
.empty { color: var(--text-secondary); font-style: italic; padding: 16px; }
footer { border-top: 1px solid var(--border); margin-top: 32px; padding-top: 12px; color: var(--text-secondary); font-size: 12px; }
"""


def render_page(title, body_html):
    """Wrap body HTML in a full page with embedded CSS.

    Args:
        title: Page title string.
        body_html: Inner body HTML content.

    Returns:
        Complete HTML document string.
    """
    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<style>{CSS}</style>
</head>
<body>
{body_html}
<footer>Generated by GE Shader Diagnostics Tool</footer>
</body>
</html>"""


def render_summary_cards(cards):
    """Render a grid of summary statistic cards.

    Args:
        cards: List of dicts with keys 'label', 'value', 'class' (optional CSS class for value).

    Returns:
        HTML string for the summary grid.
    """
    items = []
    for card in cards:
        value_class = card.get("class", "")
        value_attr = f' class="{html.escape(value_class)}"' if value_class else ""
        items.append(
            f'<div class="card">'
            f'<p class="card-label">{html.escape(card["label"])}</p>'
            f'<p class="card-value"{value_attr}>{html.escape(str(card["value"]))}</p>'
            f'</div>'
        )
    return f'<div class="summary-grid">{"".join(items)}</div>'


def render_shader_table(shaders):
    """Render shader details as an HTML table with expandable source code.

    Args:
        shaders: List of shader dicts with keys 'hash', 'source_length', 'source_text', 'call_sites'.

    Returns:
        HTML string for the shader table.
    """
    rows = []
    for shader in shaders:
        hash_short = shader["hash"][:16] + "..."
        sites_html = "".join(
            f'<div class="call-site">{html.escape(s["file"])}:{html.escape(s["function"])}:{s["line"]}</div>'
            for s in shader["call_sites"]
        )
        if not sites_html:
            sites_html = '<div class="call-site">—</div>'

        source_html = ""
        if shader["source_text"]:
            escaped_src = html.escape(shader["source_text"])
            line_count = len(shader["source_text"].split("\n"))
            source_html = (
                f'<details><summary>Source code ({line_count} lines)</summary>'
                f'<div class="source-code">{escaped_src}</div></details>'
            )

        rows.append(
            f'<tr>'
            f'<td class="hash">{html.escape(hash_short)}</td>'
            f'<td>{shader["source_length"]}</td>'
            f'<td>{sites_html}</td>'
            f'<td>{source_html}</td>'
            f'</tr>'
        )

    return (
        f'<table>'
        f'<thead><tr><th>Hash</th><th>Source Length</th><th>Call Sites</th><th>Source</th></tr></thead>'
        f'<tbody>{"".join(rows)}</tbody>'
        f'</table>'
    )


def render_diff_summary(summary):
    """Render diff summary as cards with color-coded values.

    Args:
        summary: Dict with keys 'added', 'removed', 'common', 'changed_call_sites', 'source_integrity_issues'.

    Returns:
        HTML string for the summary grid.
    """
    cards = [
        {"label": "Added", "value": summary["added"], "class": "green"},
        {"label": "Removed", "value": summary["removed"], "class": "red"},
        {"label": "Common", "value": summary["common"], "class": ""},
        {"label": "Changed Sites", "value": summary["changed_call_sites"], "class": "amber"},
    ]
    return render_summary_cards(cards)


def _render_source_details(source_text):
    """Render expandable source code details for a shader in a diff section.

    Args:
        source_text: Shader source text string, or empty string if unavailable.

    Returns:
        HTML string with <details>/<summary> element.
    """
    if not source_text:
        return '<div class="call-site" style="color:var(--text-secondary)">Source not available</div>'
    escaped_src = html.escape(source_text)
    line_count = len(source_text.split("\n"))
    return (
        f'<details><summary>Source code ({line_count} lines)</summary>'
        f'<div class="source-code">{escaped_src}</div></details>'
    )


def render_added_section(added_shaders):
    """Render the 'added shaders' section of a diff.

    Args:
        added_shaders: List of shader dicts with 'hash', 'source_length', 'call_sites', 'source_text'.

    Returns:
        HTML string.
    """
    if not added_shaders:
        return ""
    items = []
    for shader in added_shaders:
        hash_short = shader["hash"][:16] + "..."
        sites_html = "".join(
            f'<div class="call-site">{html.escape(s["file"])}:{html.escape(s["function"])}:{s["line"]}</div>'
            for s in shader["call_sites"]
        )
        source_html = _render_source_details(shader.get("source_text", ""))
        items.append(
            f'<div>'
            f'<span class="hash">{html.escape(hash_short)}</span> '
            f'(srcLen={shader["source_length"]})'
            f'{sites_html}'
            f'{source_html}'
            f'</div>'
        )
    return (
        f'<div class="section section-added">'
        f'<h3>Added Shaders ({len(added_shaders)})</h3>'
        f'{"".join(items)}'
        f'</div>'
    )


def render_removed_section(removed_shaders):
    """Render the 'removed shaders' section of a diff.

    Args:
        removed_shaders: List of shader dicts with 'hash', 'source_length', 'call_sites', 'source_text'.

    Returns:
        HTML string.
    """
    if not removed_shaders:
        return ""
    items = []
    for shader in removed_shaders:
        hash_short = shader["hash"][:16] + "..."
        sites_html = "".join(
            f'<div class="call-site">{html.escape(s["file"])}:{html.escape(s["function"])}:{s["line"]}</div>'
            for s in shader["call_sites"]
        )
        source_html = _render_source_details(shader.get("source_text", ""))
        items.append(
            f'<div>'
            f'<span class="hash">{html.escape(hash_short)}</span> '
            f'(srcLen={shader["source_length"]})'
            f'{sites_html}'
            f'{source_html}'
            f'</div>'
        )
    return (
        f'<div class="section section-removed">'
        f'<h3>Removed Shaders ({len(removed_shaders)})</h3>'
        f'{"".join(items)}'
        f'</div>'
    )


def render_changed_section(changed_sites):
    """Render the 'changed call sites' section of a diff.

    Args:
        changed_sites: List of dicts with 'hash', 'left_sites', 'right_sites', 'source_text'.

    Returns:
        HTML string.
    """
    if not changed_sites:
        return ""
    items = []
    for entry in changed_sites:
        hash_short = entry["hash"][:16] + "..."
        left_html = "".join(
            f'<div class="call-site site-left">{html.escape(s["file"])}:{html.escape(s["function"])}:{s["line"]}</div>'
            for s in entry["left_sites"]
        )
        right_html = "".join(
            f'<div class="call-site site-right">{html.escape(s["file"])}:{html.escape(s["function"])}:{s["line"]}</div>'
            for s in entry["right_sites"]
        )
        source_html = _render_source_details(entry.get("source_text", ""))
        items.append(
            f'<div>'
            f'<span class="hash">{html.escape(hash_short)}</span>'
            f'{source_html}'
            f'<div style="margin-left:16px">'
            f'<div><strong>Left:</strong>{left_html}</div>'
            f'<div><strong>Right:</strong>{right_html}</div>'
            f'</div>'
            f'</div>'
        )
    return (
        f'<div class="section section-changed">'
        f'<h3>Changed Call Sites ({len(changed_sites)})</h3>'
        f'{"".join(items)}'
        f'</div>'
    )


def render_empty_diff():
    """Render the 'no differences' message for identical collections.

    Returns:
        HTML string.
    """
    return '<div class="empty">No differences found. Both collections are identical.</div>'