/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "ge_visual_effect_impl.h"

#include "ge_external_dynamic_loader.h"
#include "ge_log.h"
#include "ge_params_reflection.h"

namespace OHOS {
namespace Rosen {
namespace Drawing {

static GEFilterType GetParamlessFilterType(const std::string& name)
{
    // Handle special cases for compatibility
    // Not recommended to add more types here
    if (name == GE_SHAPE_SDF_EMPTY_SHAPE) {
        return GEFilterType::SDF_EMPTY_SHAPE;
    }
    return GEFilterType::NONE;
}

GEVisualEffectImpl::GEVisualEffectImpl(const std::string& name, const std::optional<Drawing::CanvasInfo>& canvasInfo)
{
    // Initialize filter type from name using generated helper
    filterType_ = GEParamsBuilder::GetFilterTypeFromString(name);

    if (filterType_ == FilterType::NONE) {
        filterType_ = GetParamlessFilterType(name);
        if (filterType_ == FilterType::NONE) {
            GE_LOGE("GEVisualEffectImpl: unknown filter type for name '%s'", name.c_str());
        }
    }

    // Build params of appropriate type using generated helper
    params_ = GEParamsBuilder::Build(filterType_);
    if (!params_) {
        GE_LOGE("GEVisualEffectImpl: failed to build params for filter type '%d' with name '%s'",
            static_cast<int>(filterType_), name.c_str());
        filterType_ = FilterType::NONE; // Reset to NONE if build failed
    }

    canvasInfo_ = canvasInfo ? *canvasInfo : Drawing::CanvasInfo{};
}

GEVisualEffectImpl::~GEVisualEffectImpl() {}

const std::shared_ptr<Drawing::GEShaderShape> GEVisualEffectImpl::GetGEShaderShape(const std::string& tag) const
{
    if (!params_) {
        GE_LOGE("GEVisualEffectImpl::GetGEShaderShape: params not initialized");
        return nullptr;
    }

    auto shaderShapeTag = GEParamsMemberHelper::GEParamsMemberTagFromString(tag);
    if (shaderShapeTag == GEParamsMemberTag::INVALID) {
        return nullptr;
    }

    auto tagType = GEParamsMemberHelper::GetFilterTypeFromTag(shaderShapeTag);
    if (tagType != params_->GetType()) {
        return nullptr;
    }

    switch (shaderShapeTag) {
        case GEParamsMemberTag::FROSTED_GLASS_SDF_SHAPE: {
            auto frostedGlassParams = GEFilterParams::Unbox<GEFrostedGlassShaderFilterParams>(*params_);
            if (frostedGlassParams != nullptr) {
                return frostedGlassParams->sdfShape;
            }
            break;
        }
        case GEParamsMemberTag::FROSTED_GLASS_EFFECT_SDF_SHAPE: {
            auto frostedGlassEffectParams = GEFilterParams::Unbox<GEFrostedGlassEffectParams>(*params_);
            if (frostedGlassEffectParams != nullptr) {
                return frostedGlassEffectParams->sdfShape;
            }
            break;
        }
        default:
            break;
    }

    return nullptr;
}

#define IMPLEMENT_SET_PARAM_INTERNAL(Type)                                                                      \
    void GEVisualEffectImpl::SetParamInternal(GEFilterParams& params, GEParamsMemberTag tag, const Type& value) \
    {                                                                                                           \
        GEParamsMemberHelper::SetParamsMemberByTag(params, tag, value);                                         \
    }

FOR_EACH_PARAM_TYPE(IMPLEMENT_SET_PARAM_INTERNAL)
#undef IMPLEMENT_SET_PARAM_INTERNAL

void GEVisualEffectImpl::SetParamInternal(GEFilterParams&, GEParamsMemberTag, const long&)
{
    // Compatibility placeholder, remove this function placeholder if future effects use any long long params
    // It will be generated by IMPLEMENT_SET_PARAM_INTERNAL
}

void GEVisualEffectImpl::SetParamInternal(GEFilterParams&, GEParamsMemberTag, const long long&)
{
    // Compatibility placeholder, remove this function placeholder if future effects use any long long params
    // It will be generated by IMPLEMENT_SET_PARAM_INTERNAL
}

void GEVisualEffectImpl::SetParamInternal(GEFilterParams&, GEParamsMemberTag, const double&)
{
    // Compatibility placeholder, remove this function placeholder if future effect use any double params
    // It will be generated by IMPLEMENT_SET_PARAM_INTERNAL
}

void GEVisualEffectImpl::SetParamInternal(
    GEFilterParams&, GEParamsMemberTag, const std::shared_ptr<Drawing::ColorFilter>)
{
    // Compatibility placeholder, remove this function placeholder if future effect use any ColorFilter params
    // It will be generated by IMPLEMENT_SET_PARAM_INTERNAL
}

void GEVisualEffectImpl::SetSDFEdgeLightParams(const std::string& tag, float param)
{
    SetParam(tag, param);
}

void GEVisualEffectImpl::MakeSDFUnionOpShapeParams(const GESDFUnionOp& op)
{
    auto params = std::make_shared<GESDFUnionOpShapeParams>();
    params->op = op;
    filterType_ = FilterType::SDF_UNION_OP;
    params_ = GEFilterParams::Box(params);
}

} // namespace Drawing
} // namespace Rosen
} // namespace OHOS
