/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "core/ge_visual_effect_impl_v2.h"

#include "effect/ge_params_reflection_v2.h"
#include "ge_external_dynamic_loader.h"
#include "ge_log.h"

namespace OHOS {
namespace Rosen {
namespace Drawing {

GEVisualEffectImpl::GEVisualEffectImpl(
    const std::string& name, const std::optional<Drawing::CanvasInfo>& canvasInfo)
    : canvasInfo_(canvasInfo ? *canvasInfo : Drawing::CanvasInfo {})
{
    // Initialize filter type from name using generated helper
    filterType_ = GEParamsBuilder::GetFilterTypeFromString(name);

    // Build params of appropriate type using generated helper
    params_ = GEParamsBuilder::Build(filterType_);
}

GEVisualEffectImpl::~GEVisualEffectImpl() {}

const std::shared_ptr<Drawing::GEShaderShape> GEVisualEffectImpl::GetGEShaderShape(const std::string& tag) const
{
    auto shaderShapeTag = GEParamsMemberHelper::GEParamsMemberTagFromString(tag);
    if (shaderShapeTag == GEParamsMemberTag::INVALID) {
        return nullptr;
    }

    auto tagType = GEParamsMemberHelper::GetFilterTypeFromTag(shaderShapeTag);
    if (tagType != params_->GetType()) {
        return nullptr;
    }

    switch (shaderShapeTag) {
        case GEParamsMemberTag::FROSTED_GLASS_SDF_SHAPE: {
            auto frostedGlassParams =
                GEFilterParams::Unbox<GEFrostedGlassShaderFilterParams>(params_);
            if (frostedGlassParams != nullptr) {
                return frostedGlassParams->sdfShape;
            }
            break;
        }
        case GEParamsMemberTag::FROSTED_GLASS_EFFECT_SDF_SHAPE: {
            auto frostedGlassEffectParams =
                GEFilterParams::Unbox<GEFrostedGlassEffectParams>(params_);
            if (frostedGlassEffectParams != nullptr) {
                return frostedGlassEffectParams->sdfShape;
            }
            break;
        }
        default:
            break;
    }

    return nullptr;
}

#define IMPLEMENT_SET_PARAM_INTERNAL(Type)                                                      \
    void GEVisualEffectImpl::SetParamInternal(GEParamsMemberTag tag, const Type& value) \
    {                                                                                           \
        if (!params_) {                                                                         \
            return;                                                                             \
        }                                                                                       \
        GEParamsMemberHelper::SetParamsMemberByTag(params_, tag, value);                  \
    }

FOR_EACH_PARAM_TYPE(IMPLEMENT_SET_PARAM_INTERNAL)
#undef IMPLEMENT_SET_PARAM_INTERNAL

void GEVisualEffectImpl::SetParamInternal(GEParamsMemberTag tag, const long long& value)
{
    // Current placeholder no-op, remove this function placeholder if future effect use any long long params
    // It will be generated by IMPLEMENT_SET_PARAM_INTERNAL
}
void GEVisualEffectImpl::SetParamInternal(GEParamsMemberTag tag, const double& value)
{
    // Current placeholder no-op, remove this function placeholder if future effect use any double params
    // It will be generated by IMPLEMENT_SET_PARAM_INTERNAL
}

void GEVisualEffectImpl::SetSDFEdgeLightParams(const std::string& tag, float param)
{
    SetParam(tag, param);
}

void GEVisualEffectImpl::MakeSDFUnionOpShapeParams(const GESDFUnionOp& op)
{
    auto params = std::make_shared<GESDFUnionOpShapeParams>();
    params->op = op;
    params_ = GEFilterParams::Box(params);
}


} // namespace Drawing
} // namespace Rosen
} // namespace OHOS
