#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright (c) 2026 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Generate C++ static reflection metadata from .params files.

This script provides a best-in-effort C++ attribute parser to generate metadata for GE Effect Params
"""

import sys
import argparse
import json
import re
from pathlib import Path
from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

# Import parser modules
from tool.generate_metadata.cpp_parser import CppParser, StructInfo, FieldInfo
from tool.generate_metadata.cpp_tokenizer import CppTokenizer
from tool.generate_metadata.value_parser import infer_numeric_type, parse_component_values

# Import CLI utilities
from tool.generate_metadata.cli_utils import Console, find_clang_format, format_file_with_clang_format

# Global console instance
console = Console()


@dataclass
class FilterTypeMacroInfo:
    """Information about DECLARE_GEFILTER_TYPEFUNC macro usage."""

    filter_class: str
    params_type: str
    header_file: str


@dataclass
class FieldTagInfo:
    """Information about a field tag generated by iterate_field_tags."""

    tag_name: str
    prop_name: str
    is_array_element: bool
    array_index: Optional[int]
    prop_attr_index: int


# Copyright header for generated files
COPYRIGHT_HEADER = """/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// AUTO GENERATED BY tools/generate_metadata/gen_metadata.py
// DO NOT EDIT MANUALLY
"""


def load_config(config_path: Path) -> Tuple[Dict[str, str], Dict[str, str]]:
    """Load type aliases and blocked types from config.json."""
    type_aliases = {}
    blocked_types = {}
    try:
        with open(config_path, "r", encoding="utf-8") as f:
            config = json.load(f)
            type_aliases = config.get("type_aliases", {})
            blocked_types_list = config.get("member_setter_blocked_types", [])
            for item in blocked_types_list:
                if "type" in item:
                    blocked_types[item["type"]] = item.get("reason", "")
    except FileNotFoundError:
        console.warning(f"Config file not found at {config_path}")
    except json.JSONDecodeError as e:
        console.warning(f"Failed to parse config file: {e}")
    return type_aliases, blocked_types


def normalize_type(type_str: str, type_aliases: Dict[str, str]) -> str:
    """Normalize a type string using type aliases and removing unnecessary spaces.

    Spaces are removed except:
    - Between type qualifiers (const, volatile, mutable) and next token
    - Between type modifiers (unsigned, signed, short, long) and next token
    - After commas inside template parameters
    """
    # First apply type aliases
    type_str = type_aliases.get(type_str, type_str)

    # Keywords that should preserve space after them
    preserve_space_keywords = {"const", "volatile", "mutable", "unsigned", "signed", "short", "long"}

    # Tokenize type string, preserving structure
    # We need to track template depth to know when we're inside <...>
    tokens = []
    depth = 0
    i = 0
    while i < len(type_str):
        ch = type_str[i]

        # Track template depth
        if ch == "<":
            depth += 1
            tokens.append(ch)
            i += 1
        elif ch == ">":
            depth = max(0, depth - 1)
            tokens.append(ch)
            i += 1
        elif ch == ",":
            # Commas are preserved inside templates
            tokens.append(ch)
            i += 1
        elif ch in [" ", "\t", "\n"]:
            # Collect all whitespace
            ws = ch
            i += 1
            while i < len(type_str) and type_str[i] in [" ", "\t", "\n"]:
                ws += type_str[i]
                i += 1
            tokens.append(("ws", ws))
        elif ch in ["*", "&"]:
            tokens.append(ch)
            i += 1
        elif ch == ":" and i + 1 < len(type_str) and type_str[i + 1] == ":":
            tokens.append("::")
            i += 2
        else:
            # Collect identifier/keyword
            ident = ch
            i += 1
            while i < len(type_str) and (type_str[i].isalnum() or type_str[i] == "_"):
                ident += type_str[i]
                i += 1
            tokens.append(ident)

    # Build normalized string
    result = []
    i = 0
    while i < len(tokens):
        token = tokens[i]

        # Skip whitespace
        if isinstance(token, tuple) and token[0] == "ws":
            i += 1
            continue

        # Add token
        result.append(token)

        # Check if we need to preserve space after this token
        if token == ",":
            # Add a space after comma (for template parameters)
            result.append(" ")
        elif token in preserve_space_keywords:
            # Look ahead to see if there's a non-whitespace token
            j = i + 1
            while j < len(tokens):
                next_token = tokens[j]
                if isinstance(next_token, tuple) and next_token[0] == "ws":
                    j += 1
                    continue
                break

            if j < len(tokens) and tokens[j] not in ["<", ">", "::", "*", "&", ","]:
                # Add a space
                result.append(" ")

        i += 1

    return "".join(result)


def parse_def_file(file_path: Path, report_errors: bool = True) -> Optional[StructInfo]:
    """Parse a .params file and extract struct information."""
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Tokenize
    tokenizer = CppTokenizer(content)
    tokens = tokenizer.tokenize()

    # Parse
    parser = CppParser(tokens, str(file_path))
    structs = parser.parse()

    # Report errors if requested
    if report_errors and parser.errors:
        for error in parser.errors:
            console.error(f"  {error}")

    # Return the first (and typically only) struct
    if structs:
        return structs[0]
    return None


def scan_declare_gefilter_typefunc(effect_dirs: List[Path]) -> List[FilterTypeMacroInfo]:
    """Scan effect directories for DECLARE_GEFILTER_TYPEFUNC macro usage."""
    macro_infos = []

    for effect_dir in effect_dirs:
        # Find all .h files in the directory
        header_files = list(effect_dir.glob("*.h"))
        for header_file in header_files:
            try:
                with open(header_file, "r", encoding="utf-8") as f:
                    content = f.read()

                # Pattern to match DECLARE_GEFILTER_TYPEFUNC(Class, ParamsType)
                pattern = r"DECLARE_GEFILTER_TYPEFUNC\s*\(\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*,\s*([a-zA-Z_][a-zA-Z0-9_:<>:]*)\s*\)"

                matches = re.finditer(pattern, content)
                for match in matches:
                    filter_class = match.group(1)
                    params_type = match.group(2)

                    # Get relative path from include directory
                    # effect_dir is like: .../include/effect/filter
                    # We want: effect/filter/xxx.h
                    # header_file is like: .../include/effect/filter/xxx.h
                    # We need to get the path relative to include/
                    include_dir = header_file.parent.parent.parent  # .../include
                    rel_path = header_file.relative_to(include_dir)
                    header_include = str(rel_path)

                    macro_infos.append(FilterTypeMacroInfo(filter_class=filter_class, params_type=params_type, header_file=header_include))
            except Exception as e:
                console.warning(f"Failed to scan {header_file}: {e}")

    return macro_infos


def to_upper_case(name: str) -> str:
    """Convert camelCase or snake_case to UPPER_CASE."""
    if name.endswith("_"):
        name = name[:-1]
    result = []
    for c in name:
        if c.isupper():
            if result:
                result.append("_")
            result.append(c)
        else:
            result.append(c.upper())
    return "".join(result)


def to_pascal_case(name: str) -> str:
    """Convert snake_case or camelCase to PascalCase.

    Examples:
        propName -> PropName
        prop_name -> PropName
        _propName -> PropName (strip leading underscore)
    """
    # Remove trailing underscore
    if name.endswith("_"):
        name = name[:-1]
    # Remove leading underscore
    if name.startswith("_"):
        name = name[1:]

    if not name:
        return name

    # Convert to PascalCase
    result = []
    capitalize_next = True
    for c in name:
        if c == "_":
            capitalize_next = True
        elif capitalize_next:
            result.append(c.upper())
            capitalize_next = False
        else:
            result.append(c)
    return "".join(result)


def get_effective_type_for_tag(
    field: FieldInfo, is_array_elem: bool, array_idx: Optional[int], prop_attr_index: int, type_aliases: Dict[str, str]
) -> str:
    """Get the effective type for a field tag.

    This function consolidates the logic for determining the effective type
    that was duplicated in generate_set_params_member_overloads_impl() and collect_effective_types().

    Args:
        field: The field info
        is_array_elem: Whether this is an array element tag
        array_idx: The array index (if is_array_element is True)
        prop_attr_index: The index of the prop attribute to use for cast_from
        type_aliases: Type alias mapping

    Returns:
        The normalized effective type string
    """
    cast_from_type = None
    if field.prop_attributes and prop_attr_index < len(field.prop_attributes):
        cast_from_type = field.prop_attributes[prop_attr_index].cast_from

    if cast_from_type:
        effective_type = cast_from_type
    elif is_array_elem and field.prop_attributes:
        for prop_attr in field.prop_attributes:
            if prop_attr.array_accessor_length is not None:
                if prop_attr.array_accessor_type:
                    effective_type = prop_attr.array_accessor_type
                else:
                    effective_type = field.type
                break
    else:
        effective_type = field.type

    return normalize_type(effective_type, type_aliases)


def get_original_field_type(field: FieldInfo, is_array_elem: bool) -> str:
    """Get the original field type (before cast_from consideration).

    Args:
        field: The field info
        is_array_elem: Whether this is an array element tag

    Returns:
        The original field type string
    """
    if is_array_elem and field.prop_attributes:
        for prop_attr in field.prop_attributes:
            if prop_attr.array_accessor_length is not None:
                if prop_attr.array_accessor_type:
                    return prop_attr.array_accessor_type
                else:
                    return field.type
    return field.type


def has_cast_from(field: FieldInfo, prop_attr_index: int) -> bool:
    """Check if field has cast_from_from specified.

    Args:
        field: The field info
        prop_attr_index: The index of the prop attribute to check

    Returns:
        True if cast_from is specified, False otherwise
    """
    if field.prop_attributes and prop_attr_index < len(field.prop_attributes):
        return field.prop_attributes[prop_attr_index].cast_from is not None
    return False


def to_member_tag_name(enum_type: str, field_name: str, index: Optional[int] = None) -> str:
    """Generate GEParamsMemberTag enum name.

    Args:
        enum_type: The enum type (e.g., BEZIER_WARP)
        field_name: The field name (e.g., destinationPatch)
        index: Optional index for array accessor fields (e.g., 0 for destinationPatch[0])
    """
    field_upper = to_upper_case(field_name)
    if index is not None:
        return f"{enum_type}_{field_upper}{index}"
    return f"{enum_type}_{field_upper}"


def get_effective_prop_name(field: FieldInfo, filter_name: str, index: Optional[int] = None) -> str:
    """Get the effective property name for a field.

    Args:
        field: The field info
        filter_name: The filter name
        index: Optional index for array accessor fields

    Note:
        Uses PascalCase as default for fields without explicit [[ge::prop]].
        Fields that need UPPER_CASE naming should use explicit [[ge::prop("UPPER_CASE_NAME")]].
    """
    if field.prop_name:
        if index is not None:
            return f"{field.prop_name}{index}"
        return field.prop_name
    # Use PascalCase as default for fields without explicit prop
    base_name = to_pascal_case(field.name)
    if index is not None:
        return f"{filter_name}_{base_name}{index}"
    return f"{filter_name}_{base_name}"


def iterate_field_tags(struct: StructInfo, field: FieldInfo):
    """Helper to iterate over all tags for a field.

    Yields FieldTagInfo objects containing tag information.
    For array elements, array_index is the element index.
    For whole-field accessors, is_array_element is False and array_index is None.
    """
    enum_type = struct.enum_type

    if field.prop_attributes:
        for prop_attr_idx, prop_attr in enumerate(field.prop_attributes):
            if prop_attr.array_accessor_length is not None:
                # Generate tags for each array element
                for i in range(prop_attr.array_accessor_length):
                    tag_name = to_member_tag_name(enum_type, field.name, i)
                    prop = f"{prop_attr.name}{i}"
                    yield FieldTagInfo(tag_name, prop, True, i, prop_attr_idx)
            else:
                # Single tag for whole-field accessor
                tag_name = to_member_tag_name(enum_type, field.name)
                # If prop_attr.name is empty, auto-generate from field name
                if prop_attr.name:
                    prop = prop_attr.name
                else:
                    prop = get_effective_prop_name(field, struct.filter_name)
                yield FieldTagInfo(tag_name, prop, False, None, prop_attr_idx)
    else:
        # No prop_attributes: single tag for field
        tag_name = to_member_tag_name(enum_type, field.name)
        prop = get_effective_prop_name(field, struct.filter_name)
        yield FieldTagInfo(tag_name, prop, False, None, 0)


def generate_member_enums(structs: List[StructInfo]) -> Tuple[str, Dict[str, Tuple[int, int, str]]]:
    """Generate GEParamsMemberTag enum."""
    output = []

    # Generate member tag enum
    output.append("// Enum for all parameter member tags")
    output.append("enum class GEParamsMemberTag : uint32_t {")
    output.append("    INVALID = 0,")

    tag_count = 1
    struct_tag_ranges = {}
    for struct in structs:
        first_tag = tag_count
        enum_start = struct.enum_type

        for field in struct.fields:
            for tag_info in iterate_field_tags(struct, field):
                output.append(f"    {tag_info.tag_name},")
                tag_count += 1

        last_tag = tag_count - 1
        struct_tag_ranges[struct.name] = (first_tag, last_tag, enum_start)

    output.append("};")
    output.append("")
    return "\n".join(output), struct_tag_ranges


def generate_struct_tag_ranges_decl(structs: List[StructInfo], type_aliases: Dict[str, str], blocked_types: Dict[str, str] = None) -> str:
    """Generate GEParamsMemberHelper class declaration."""
    if blocked_types is None:
        blocked_types = {}

    output = []

    output.append("")
    output.append("// Static helper class for params member tag operations")
    output.append("class GEParamsMemberHelper {")
    output.append("public:")
    output.append("    // Convert GEParamsMemberTag to corresponding GEFilterType")
    output.append("    static GEFilterType GetFilterTypeFromTag(GEParamsMemberTag tag);")

    output.append("")
    output.append("    // Convert string to GEParamsMemberTag")
    output.append("    // Note: Strings are sourced from GEParamsFieldAccessor<Tag>::name for single source of truth")
    output.append("    //       Aliases from [[ge::prop_alias]] are also included")
    output.append("    static GEParamsMemberTag GEParamsMemberTagFromString(const std::string& str);")

    output.append("")
    output.append("    // Set params member by tag using overloaded functions (reduces binary bloat)")
    output.append("    // All implementations are in the .cpp file")
    output.append(generate_set_params_member_overloads_decl(structs, type_aliases, blocked_types))

    output.append("};")
    output.append("")

    return "\n".join(output)


def generate_get_filter_type_from_tag_impl(structs: List[StructInfo]) -> str:
    """Generate GEParamsMemberHelper::GetFilterTypeFromTag() implementation."""
    output = []

    output.append("GEFilterType GEParamsMemberHelper::GetFilterTypeFromTag(GEParamsMemberTag tag)")
    output.append("{")
    output.append("    switch (tag) {")

    output.append("#define GE_GET_FILTER_TYPE_CASE(Tag, FilterTypeEnum) \\")
    output.append("    case GEParamsMemberTag::Tag: {                   \\")
    output.append("        return GEFilterType::FilterTypeEnum;         \\")
    output.append("    }")
    output.append("")

    for struct in structs:
        enum_type = struct.enum_type
        for field in struct.fields:
            for tag_info in iterate_field_tags(struct, field):
                output.append(f"        GE_GET_FILTER_TYPE_CASE({tag_info.tag_name}, {enum_type})")

    output.append("        default:")
    output.append("            return GEFilterType::NONE;")
    output.append("    }")
    output.append("}")
    output.append("")
    output.append("#undef GE_GET_FILTER_TYPE_CASE")
    output.append("")

    return "\n".join(output)


def generate_set_params_member_overloads_impl(structs: List[StructInfo], type_aliases: Dict[str, str], blocked_types: Dict[str, str] = None) -> str:
    """Generate overloaded SetParamsMemberByTag function implementations."""
    if blocked_types is None:
        blocked_types = {}

    output = []

    output.append("// Helper macro to validate and set parameter")
    output.append("#define GE_VALIDATE_AND_SET(Tag) \\")
    output.append("    case GEParamsMemberTag::Tag: { \\")
    output.append("        using ParamsType = GEParamsFieldAccessor<GEParamsMemberTag::Tag>::ParamsType; \\")
    output.append("        using FieldType = GEParamsFieldAccessor<GEParamsMemberTag::Tag>::FieldType; \\")
    output.append("        using SetterType = std::remove_cv_t<std::remove_reference_t<decltype(value)>>; \\")
    output.append("        auto unboxed = GEFilterParams::Unbox<ParamsType>(params); \\")
    output.append("        if (unboxed == nullptr) { \\")
    output.append("            return; \\")
    output.append("        } \\")
    output.append("        auto& actualParams = *unboxed; \\")
    output.append("        FieldType transformed; \\")
    output.append("        if (GEParamsValueTransformer<GEParamsMemberTag::Tag, SetterType, FieldType>::Transform(value, transformed)) { \\")
    output.append("            GEParamsFieldAccessor<GEParamsMemberTag::Tag>::Set(actualParams, transformed); \\")
    output.append("        } \\")
    output.append("        break; \\")
    output.append("    }")
    output.append("")

    # Group tags by their effective type (considering prop attributes and array_accessor_type)
    # When cast_from is specified, tags are added to BOTH cast_from type AND original field type
    type_to_tags = {}
    for struct in structs:
        for field in struct.fields:
            for tag_info in iterate_field_tags(struct, field):
                # Get effective type (cast_from or field type)
                normalized_type = get_effective_type_for_tag(
                    field, tag_info.is_array_element, tag_info.array_index, tag_info.prop_attr_index, type_aliases
                )

                if normalized_type not in blocked_types:
                    if normalized_type not in type_to_tags:
                        type_to_tags[normalized_type] = []
                    type_to_tags[normalized_type].append((tag_info.tag_name, struct.name, field.name))

                # If cast_from is specified, also add to original field type group
                if has_cast_from(field, tag_info.prop_attr_index):
                    original_type = get_original_field_type(field, tag_info.is_array_element)
                    normalized_original = normalize_type(original_type, type_aliases)

                    if normalized_original not in blocked_types:
                        if normalized_original not in type_to_tags:
                            type_to_tags[normalized_original] = []
                        type_to_tags[normalized_original].append((tag_info.tag_name, struct.name, field.name))

    for field_type, tags in sorted(type_to_tags.items()):
        output.append(f"void GEParamsMemberHelper::SetParamsMemberByTag(GEFilterParams& params,")
        output.append(f"    GEParamsMemberTag tag, const {field_type}& value)")
        output.append("{")
        output.append("")
        output.append("    auto expectedFilterType = GetFilterTypeFromTag(tag);")
        output.append("    if (params.GetType() != expectedFilterType) {")
        output.append("        return;")
        output.append("    }")
        output.append("")
        output.append("    switch (tag) {")

        for tag_name, struct_name, field_name in tags:
            output.append(f"        GE_VALIDATE_AND_SET({tag_name})")

        output.append("        default:")
        output.append(f'            GE_LOGE("SetParamsMemberByTag<{field_type}>: No matching case for tag %u (filter type %u, params type %u)",')
        output.append("                static_cast<uint32_t>(tag),")
        output.append("                static_cast<uint32_t>(expectedFilterType),")
        output.append("                static_cast<uint32_t>(params.GetType()));")
        output.append("            break;")
        output.append("    }")
        output.append("}")
        output.append("")

    output.append("#undef GE_VALIDATE_AND_SET")
    output.append("")

    return "\n".join(output)


def generate_filter_params_type_info(structs: List[StructInfo]) -> str:
    """Generate GEFilterParamsTypeInfo template specializations."""
    output = []

    output.append("// GEFilterParamsTypeInfo template specializations")
    output.append("// Provides FilterType ID and FilterName for each params type")
    output.append("template<typename T>")
    output.append("struct GEFilterParamsTypeInfo {")
    output.append("    using Self = T;")
    output.append("    static constexpr GEFilterType ID = GEFilterType::NONE;")
    output.append('    static constexpr std::string_view FilterName = "";')
    output.append("};")
    output.append("")

    output.append("// Helper macro for GEParamsTypeInfo specializations")
    output.append("#define GE_PARAMS_TYPE_INFO(Struct, FilterTypeEnum, FilterNameStr) \\")
    output.append("    template<> \\")
    output.append("    struct GEFilterParamsTypeInfo<Struct> { \\")
    output.append("        using Self = Struct; \\")
    output.append("        static constexpr GEFilterType ID = GEFilterType::FilterTypeEnum; \\")
    output.append("        static constexpr std::string_view FilterName = #FilterNameStr; \\")
    output.append("    }")
    output.append("")

    for struct in structs:
        enum_type = struct.enum_type
        struct_name = struct.name
        filter_name = struct.filter_name
        output.append(f"GE_PARAMS_TYPE_INFO({struct_name}, {enum_type}, {filter_name});")

    output.append("")
    output.append("#undef GE_PARAMS_TYPE_INFO")
    output.append("")

    return "\n".join(output)


def generate_type_traits(structs: List[StructInfo]) -> str:
    """Generate type traits for parameter structs."""
    output = []

    output.append("// Type traits for accessing struct fields")
    output.append("template<GEParamsMemberTag Tag>")
    output.append("struct GEParamsFieldAccessor;")
    output.append("")

    output.append("// Helper macro for generating field accessors")
    output.append("#define GE_PARAMS_FIELD_ACCESSOR(Struct, Field, Tag, PropName) \\")
    output.append("    template<> \\")
    output.append("    struct GEParamsFieldAccessor<GEParamsMemberTag::Tag> { \\")
    output.append("        using ParamsType = Struct; \\")
    output.append("        using FieldType = decltype(Struct::Field); \\")
    output.append("        static constexpr const char name[] = #PropName; \\")
    output.append("        static FieldType& Get(ParamsType& params) { return params.Field; } \\")
    output.append("        static const FieldType& Get(const ParamsType& params) { return params.Field; } \\")
    output.append("        static void Set(ParamsType& params, const FieldType& value) { params.Field = value; } \\")
    output.append("    }")
    output.append("")

    # Helper macro for array element accessors
    output.append("// Helper macro for generating array element field accessors")
    output.append("#define GE_PARAMS_ARRAY_ELEMENT_ACCESSOR(Struct, Field, Index, Tag, PropName) \\")
    output.append("    template<> \\")
    output.append("    struct GEParamsFieldAccessor<GEParamsMemberTag::Tag> { \\")
    output.append("        using ParamsType = Struct; \\")
    output.append("        using FieldType = typename decltype(Struct::Field)::value_type; \\")
    output.append("        static constexpr const char* name = #PropName; \\")
    output.append("        static FieldType& Get(ParamsType& params) { return params.Field[Index]; } \\")
    output.append("        static const FieldType& Get(const ParamsType& params) { return params.Field[Index]; } \\")
    output.append("        static void Set(ParamsType& params, const FieldType& value) { params.Field[Index] = value; } \\")
    output.append("    }")
    output.append("")

    for struct in structs:
        for field in struct.fields:
            for tag_info in iterate_field_tags(struct, field):
                if tag_info.is_array_element:
                    output.append(
                        f"GE_PARAMS_ARRAY_ELEMENT_ACCESSOR({struct.name}, {field.name}, {tag_info.array_index}, {tag_info.tag_name}, {tag_info.prop_name});"
                    )
                else:
                    output.append(f"GE_PARAMS_FIELD_ACCESSOR({struct.name}, {field.name}, {tag_info.tag_name}, {tag_info.prop_name});")

    output.append("")
    output.append("#undef GE_PARAMS_FIELD_ACCESSOR")
    output.append("#undef GE_PARAMS_ARRAY_ELEMENT_ACCESSOR")
    output.append("")

    return "\n".join(output)


def generate_set_member_cases(structs: List[StructInfo]) -> str:
    """Generate switch cases for SetParamsMemberByTag template function."""
    output = []

    output.append("#define GE_SET_MEMBER_CASE(Tag) \\")
    output.append("    case GEParamsMemberTag::Tag: \\")
    output.append("        if constexpr (std::is_same_v<ParamsType, GEParamsFieldAccessor<GEParamsMemberTag::Tag>::ParamsType>) {{ \\")
    output.append("            auto transformed = GEParamsValueTransformer<GEParamsMemberTag::Tag, T>::Transform(value); \\")
    output.append("            GEParamsFieldAccessor<GEParamsMemberTag::Tag>::Set(params, transformed); \\")
    output.append("        }} \\")
    output.append("        break;")
    output.append("")

    for struct in structs:
        for field in struct.fields:
            for tag_info in iterate_field_tags(struct, field):
                output.append(f"        GE_SET_MEMBER_CASE({tag_info.tag_name})")

    output.append("")
    output.append("#undef GE_SET_MEMBER_CASE")
    output.append("")

    return "\n".join(output)


def generate_set_params_member_overloads_decl(structs: List[StructInfo], type_aliases: Dict[str, str], blocked_types: Dict[str, str] = None) -> str:
    """Generate overloaded SetParamsMemberByTag function declarations."""
    if blocked_types is None:
        blocked_types = {}

    output = []

    output.append("    // Overloaded SetParamsMemberByTag for each unique parameter type")

    # Collect unique effective types from all tags (same logic as generate_set_params_member_overloads_impl)
    unique_types = collect_effective_types(structs, type_aliases, blocked_types)
    sorted_types = sorted(unique_types)

    for field_type in sorted_types:
        output.append(f"    static void SetParamsMemberByTag(GEFilterParams& params,")
        output.append(f"                                     GEParamsMemberTag tag, const {field_type}& value);")

    return "\n".join(output)


def generate_string_to_enum_mapping_impl(structs: List[StructInfo]) -> str:
    """Generate GEParamsMemberHelper::GEParamsMemberTagFromString() implementation."""
    output = []

    # Collect all string-to-tag mappings, including aliases
    string_to_tags: Dict[str, List[Tuple[str, str]]] = {}
    for struct in structs:
        for field in struct.fields:
            for tag_info in iterate_field_tags(struct, field):
                # Add primary prop name
                if tag_info.prop_name not in string_to_tags:
                    string_to_tags[tag_info.prop_name] = []
                string_to_tags[tag_info.prop_name].append((struct.name, tag_info.tag_name))

                # Add alias if (for first prop attribute)
                if field.prop_attributes and not tag_info.is_array_element:
                    # Get first prop attribute
                    prop_attr = field.prop_attributes[0]
                    if prop_attr.alias:
                        if prop_attr.alias not in string_to_tags:
                            string_to_tags[prop_attr.alias] = []
                        string_to_tags[prop_attr.alias].append((struct.name, tag_info.tag_name))

    # Check for collisions
    collisions = []
    for prop_name, tags in string_to_tags.items():
        if len(tags) > 1:
            collisions.append((prop_name, tags))

    if collisions:
        error_lines = ["Error: String collision detected in GEParamsMemberTagFromString mapping:"]
        for prop_name, tags in collisions:
            error_lines.append(f"\n  String '{prop_name}' is used by multiple fields:")
            for struct_name, tag_name in tags:
                error_lines.append(f"    - {struct_name}::{tag_name}")
        console.error("\n".join(error_lines))
        raise RuntimeError("\n".join(error_lines))

    output.append("GEParamsMemberTag GEParamsMemberHelper::GEParamsMemberTagFromString(const std::string& str)")
    output.append("{")
    output.append("    static const std::unordered_map<std::string, GEParamsMemberTag> map = {")

    # Helper macro for reducing repetition - uses GEParamsFieldAccessor::name
    output.append("#define GE_STRING_TO_TAG_ENTRY(Tag) \\")
    output.append("    { GEParamsFieldAccessor<GEParamsMemberTag::Tag>::name, GEParamsMemberTag::Tag }")
    output.append("")

    # Helper macro for alias entries
    output.append("#define GE_STRING_TO_TAG_ALIAS(Tag, Alias) \\")
    output.append("    { #Alias, GEParamsMemberTag::Tag }")
    output.append("")

    for struct in structs:
        for field in struct.fields:
            for tag_info in iterate_field_tags(struct, field):
                output.append(f"        GE_STRING_TO_TAG_ENTRY({tag_info.tag_name}),")

                # Add alias entry if present (for the first prop attribute)
                if field.prop_attributes and not tag_info.is_array_element:
                    prop_attr = field.prop_attributes[0]
                    if prop_attr.alias:
                        output.append(f"        GE_STRING_TO_TAG_ALIAS({tag_info.tag_name}, {prop_attr.alias}),")

    output.append("    };")
    output.append("")
    output.append("#undef GE_STRING_TO_TAG_ENTRY")
    output.append("#undef GE_STRING_TO_TAG_ALIAS")
    output.append("")
    output.append("    auto it = map.find(str);")
    output.append("    if (it != map.end()) {")
    output.append("        return it->second;")
    output.append("    }")
    output.append("    return GEParamsMemberTag::INVALID;")
    output.append("}")
    output.append("")

    return "\n".join(output)


def generate_params_builder_decl() -> str:
    """Generate GEParamsBuilder helper class declaration."""
    output = []

    output.append("class GEParamsBuilder {")
    output.append("public:")
    output.append("    static std::unique_ptr<GEFilterParams> Build(GEFilterType filterType);")
    output.append("")
    output.append("    // Convert filter name string to GEFilterType")
    output.append("    // Note: Strings are sourced from GEFilterParamsTypeInfo<Struct>::FilterName")
    output.append("    static GEFilterType GetFilterTypeFromString(const std::string& str);")
    output.append("};")
    output.append("")

    return "\n".join(output)


def generate_params_builder_impl(structs: List[StructInfo]) -> str:
    """Generate GEParamsBuilder::Build() implementation."""
    output = []

    output.append("std::unique_ptr<GEFilterParams> GEParamsBuilder::Build(GEFilterType filterType)")
    output.append("{")
    output.append("    switch (filterType) {")
    output.append("#define GE_BUILD_PARAMS_CASE(EnumType, Struct) \\")
    output.append("    case GEFilterType::EnumType: {\\")
    output.append("        return GEFilterParams::Box(std::make_shared<Struct>()); \\")
    output.append("    }")
    output.append("")

    for struct in structs:
        enum_type = struct.enum_type
        struct_name = struct.name
        output.append(f"        GE_BUILD_PARAMS_CASE({enum_type}, {struct_name})")

    output.append("        default:")
    output.append("            return nullptr;")
    output.append("        }")
    output.append("}")
    output.append("")
    output.append("#undef GE_BUILD_PARAMS_CASE")
    output.append("")

    return "\n".join(output)


def generate_filter_type_from_string_impl(structs: List[StructInfo]) -> str:
    """Generate GEParamsBuilder::GetFilterTypeFromString() implementation."""
    output = []

    output.append("GEFilterType GEParamsBuilder::GetFilterTypeFromString(const std::string& str)")
    output.append("{")
    output.append("    static const std::unordered_map<std::string, GEFilterType> map = {")

    # Helper macro for primary filter name - uses GEFilterParamsTypeInfo::FilterName
    output.append("#define GE_FILTER_NAME_TO_TYPE_ENTRY(Struct) \\")
    output.append("    { std::string(GEFilterParamsTypeInfo<Struct>::FilterName), GEFilterParamsTypeInfo<Struct>::ID }")
    output.append("")

    # Helper macro for alias entries (struct-level alias from [[ge::params(..., alias="...")]])
    output.append("#define GE_FILTER_NAME_TO_TYPE_ALIAS(Struct, Alias) \\")
    output.append("    { #Alias, GEFilterParamsTypeInfo<Struct>::ID }")
    output.append("")

    for struct in structs:
        struct_name = struct.name
        output.append(f"        GE_FILTER_NAME_TO_TYPE_ENTRY({struct_name}),")

        # Add alias entry if struct has alias attribute
        struct_alias = struct.params.get("alias") if struct.params else None
        if struct_alias:
            output.append(f"        GE_FILTER_NAME_TO_TYPE_ALIAS({struct_name}, {struct_alias}),")

    output.append("    };")
    output.append("")
    output.append("#undef GE_FILTER_NAME_TO_TYPE_ENTRY")
    output.append("#undef GE_FILTER_NAME_TO_TYPE_ALIAS")
    output.append("")
    output.append("    auto it = map.find(str);")
    output.append("    if (it != map.end()) {")
    output.append("        return it->second;")
    output.append("    }")
    output.append("    return GEFilterType::NONE;")
    output.append("}")
    output.append("")

    return "\n".join(output)


def collect_effective_types(structs: List[StructInfo], type_aliases: Dict[str, str], blocked_types: Dict[str, str] = None) -> set:
    """Collect unique effective types from all tags.

    When cast_from is specified, both cast_from type AND original field type
    are included to generate overloads for both types.

    Args:
        structs: List of struct information
        type_aliases: Type alias mapping
        blocked_types: Dictionary of types to exclude (type -> reason mapping)

    Returns:
        Set of unique effective types, excluding any blocked types
    """
    if blocked_types is None:
        blocked_types = {}

    unique_types = set()
    for struct in structs:
        for field in struct.fields:
            for tag_info in iterate_field_tags(struct, field):
                # Get effective type (cast_from or field type)
                normalized_type = get_effective_type_for_tag(
                    field, tag_info.is_array_element, tag_info.array_index, tag_info.prop_attr_index, type_aliases
                )
                if normalized_type not in blocked_types:
                    unique_types.add(normalized_type)

                # If cast_from is specified, also add original field type
                # This ensures we generate overloads for both types
                if has_cast_from(field, tag_info.prop_attr_index):
                    original_type = get_original_field_type(field, tag_info.is_array_element)
                    normalized_original = normalize_type(original_type, type_aliases)
                    if normalized_original not in blocked_types:
                        unique_types.add(normalized_original)

    return unique_types


def generate_type_xmacro(structs: List[StructInfo], type_aliases: Dict[str, str], blocked_types: Dict[str, str] = None) -> str:
    """Generate X-Macro listing all unique member variable types."""
    if blocked_types is None:
        blocked_types = {}

    output = []

    # Collect unique effective types from all tags (same logic as generate_set_params_member_overloads_impl)
    unique_types = collect_effective_types(structs, type_aliases, blocked_types)
    sorted_types = sorted(unique_types)

    output.append("// X-Macro listing all unique parameter member types")
    output.append("// Usage: #define X(Type) <your code>; FOR_EACH_PARAM_TYPE(X); #undef X")
    output.append("#define FOR_EACH_PARAM_TYPE(X) \\")

    for i, type_name in enumerate(sorted_types):
        if i < len(sorted_types) - 1:
            output.append(f"    X(ESCAPE({type_name})) \\")
        else:
            output.append(f"    X(ESCAPE({type_name}))")

    output.append("")

    return "\n".join(output)


def simplify_params_type(full_qualified_type: str, known_params_types: List[str]) -> str:
    """Simplify a fully-qualified params type to its simple name if it matches a known params type.

    Args:
        full_qualified_type: The full-qualified type name (e.g., "Drawing::GEKawaseBlurShaderFilterParams")
        known_params_types: List of known params type names (e.g., ["GEKawaseBlurShaderFilterParams", ...])

    Returns:
        The simplified type name if a match is found, otherwise: original type

    Matching rules:
    1. Exact match with a: known params type
    2. Ends with a known params type (handles namespace prefixes)
    """
    simple_name = full_qualified_type.split("::")[-1]

    if simple_name in known_params_types:
        return simple_name

    for known_type in known_params_types:
        if full_qualified_type.endswith(known_type):
            if len(full_qualified_type) == len(known_type):
                return known_type
            # Check bounds before slicing to avoid index out of range
            elif len(known_type) + 2 <= len(full_qualified_type):
                if full_qualified_type[-len(known_type) - 2 : -len(known_type)] == "::":
                    return known_type

    return full_qualified_type


def generate_filter_type_info_v2_header(macro_infos: List[FilterTypeMacroInfo], structs: List[StructInfo]) -> str:
    """Generate GEFilterTypeInfoV2 header file content."""
    output = []

    known_params_types = [struct.name for struct in structs]

    output.append(COPYRIGHT_HEADER)
    output.append("")
    output.append("#ifndef GRAPHICS_EFFECT_GE_FILTER_TYPE_INFO_H")
    output.append("#define GRAPHICS_EFFECT_GE_FILTER_TYPE_INFO_H")
    output.append("")
    output.append("#include <type_traits>")
    output.append('#include "ge_filter_type.h"')
    output.append('#include "ge_params_reflection.h"')
    output.append("")

    # Group by header file and add includes
    header_to_macros = {}
    for info in macro_infos:
        if info.header_file not in header_to_macros:
            header_to_macros[info.header_file] = []
        header_to_macros[info.header_file].append(info)

    # Add includes for each header file
    for header_file in sorted(header_to_macros.keys()):
        output.append(f'#include "{header_file}"')
    output.append("")

    output.append("namespace OHOS {")
    output.append("namespace Rosen {")
    output.append("namespace Drawing {")
    output.append("")

    # Base template
    output.append("// GEFilterTypeInfoV2 - Type information for filter classes")
    output.append("template<typename T, typename = void>")
    output.append("struct GEFilterTypeInfoV2 {")
    output.append("    using FilterClass = T;")
    output.append("    using ParamType = void;")
    output.append("    static constexpr GEFilterType ID = GEFilterType::NONE;")
    output.append('    static constexpr std::string_view Name = "";')
    output.append("};")
    output.append("")

    # Helper macro for GEFilterTypeInfoV2 specializations
    output.append("#define GE_FILTER_TYPE_INFO(_FilterClass, _ParamType) \\")
    output.append("    template<> \\")
    output.append("    struct GEFilterTypeInfoV2<_FilterClass> { \\")
    output.append("        using FilterClass = _FilterClass; \\")
    output.append("        using ParamType = _ParamType; \\")
    output.append("        static constexpr GEFilterType ID = GEFilterParamsTypeInfo<_ParamType>::ID; \\")
    output.append("        static constexpr std::string_view Name = GEFilterParamsTypeInfo<_ParamType>::FilterName; \\")
    output.append("    }")
    output.append("")

    # Specializations for each filter class
    output.append("// Specializations for filter classes")
    output.append("// Each filter class uses DECLARE_GEFILTER_TYPEFUNC(FilterClass, ParamType)")
    output.append("")

    for info in macro_infos:
        # Simplify params type if it matches a known params type
        simplified_params_type = simplify_params_type(info.params_type, known_params_types)
        output.append(f"GE_FILTER_TYPE_INFO({info.filter_class}, {simplified_params_type});")

    output.append("")
    output.append("#undef GE_FILTER_TYPE_INFO")
    output.append("")

    output.append("} // namespace Drawing")
    output.append("} // namespace Rosen")
    output.append("} // namespace OHOS")
    output.append("")
    output.append("#endif // GRAPHICS_EFFECT_GE_FILTER_TYPE_INFO_H")

    return "\n".join(output)


def generate_min_constraint(tag: str, field_type: str, min_val: str) -> str:
    """Generate constraint metadata for min only."""
    if "{" in str(min_val):
        mins = parse_component_values(min_val)
        if mins:
            component_type = infer_numeric_type(mins[0])
            mins_str = ", ".join(mins)
            return f"GE_PARAMS_CONSTRAINT_MIN_COMPONENTS({tag}, {component_type}, {len(mins)}, ESCAPE({{{mins_str}}}));"
        else:
            console.error(f"Failed to parse min components for tag {tag} with value {min_val}")
            return ""
    else:
        return f"GE_PARAMS_CONSTRAINT_MIN({tag}, {field_type}, {min_val});"


def generate_max_constraint(tag: str, field_type: str, max_val: str) -> str:
    """Generate constraint metadata for max only."""
    if "{" in str(max_val):
        maxs = parse_component_values(max_val)
        if maxs:
            component_type = infer_numeric_type(maxs[0])
            maxs_str = ", ".join(maxs)
            return f"GE_PARAMS_CONSTRAINT_MAX_COMPONENTS({tag}, {component_type}, {len(maxs)}, ESCAPE({{{maxs_str}}}));"
        else:
            console.error(f"Failed to parse max components for tag {tag} with value {max_val}")
            return ""
    else:
        return f"GE_PARAMS_CONSTRAINT_MAX({tag}, {field_type}, {max_val});"


def generate_convert_constraint(tag: str, cast_from: str, custom: Optional[str]) -> str:
    """Generate constraint metadata for type conversion."""
    if custom:
        return f"GE_PARAMS_CONSTRAINT_CONVERT_CUSTOM({tag}, ESCAPE({cast_from}), {custom});"
    else:
        return f"GE_PARAMS_CONSTRAINT_CONVERT_CAST_FROM({tag}, ESCAPE({cast_from}));"


def generate_constraint_metadata(field_info: FieldInfo, tag: str, prop_attr_index: int = 0) -> str:
    """Generate constraint metadata for a field with prop attributes."""
    if not field_info.prop_attributes:
        return ""

    field_type = field_info.type
    output = []

    # Use the specified prop attribute for constraint metadata
    # (prop_attr_index indicates which prop attribute to use)
    prop_attr = field_info.prop_attributes[prop_attr_index]

    # Handle min constraint
    if prop_attr.min_value is not None:
        output.append(generate_min_constraint(tag, field_type, prop_attr.min_value))

    # Handle max constraint
    if prop_attr.max_value is not None:
        output.append(generate_max_constraint(tag, field_type, prop_attr.max_value))

    # Handle convert constraints (cast_from/custom)
    if prop_attr.cast_from is not None:
        output.append(generate_convert_constraint(tag, prop_attr.cast_from, prop_attr.custom))

    return "\n".join(output)


# Raw string constants for fixed template definitions
BASE_CONSTRAINT_TEMPLATES = r'''
// Base constraint templates for Min, Max, and Convert components
template<GEParamsMemberTag, typename = void>
struct GEParamsConstraintMinInfo {
    static constexpr bool HAS_MIN = false;
    static constexpr bool COMPONENT_WISE = false;
    static constexpr size_t COMPONENT_COUNT = 0;
};

template<GEParamsMemberTag, typename = void>
struct GEParamsConstraintMaxInfo {
    static constexpr bool HAS_MAX = false;
    static constexpr bool COMPONENT_WISE = false;
    static constexpr size_t COMPONENT_COUNT = 0;
};

template<GEParamsMemberTag, typename = void>
struct GEParamsConstraintConvertInfo {
    static constexpr bool HAS_CONVERT = false;
    static constexpr bool HAS_CAST_FROM = false;
    using CastFromType = void;
    static constexpr bool HAS_CUSTOM = false;
    using CustomTransformer = void;
};

template<GEParamsMemberTag Tag>
struct GEParamsConstraintInfo : GEParamsConstraintMinInfo<Tag>,
                                GEParamsConstraintMaxInfo<Tag>,
                                GEParamsConstraintConvertInfo<Tag> {
    using CastFromType = typename GEParamsConstraintConvertInfo<Tag>::CastFromType;
    using CustomTransformer = typename GEParamsConstraintConvertInfo<Tag>::CustomTransformer;

    static constexpr bool HAS_RANGE =
        GEParamsConstraintMinInfo<Tag>::HAS_MIN || GEParamsConstraintMaxInfo<Tag>::HAS_MAX;
    static constexpr bool COMPONENT_WISE =
        GEParamsConstraintMinInfo<Tag>::COMPONENT_WISE || GEParamsConstraintMaxInfo<Tag>::COMPONENT_WISE;
};

'''

VALUE_TRANSFORMER_TEMPLATE = r'''
template<GEParamsMemberTag Tag, typename FromType, typename ToType>
struct GEParamsValueTransformer {
    static bool TransformCustomConvert(const FromType& value, ToType& out)
    {
        using namespace ValueTransformerTypeTraits;
        using Constraint = GEParamsConstraintInfo<Tag>;
        using Transformer = typename Constraint::CustomTransformer;
        if constexpr (std::is_same_v<FromType, ToType>) {
            if constexpr (has_transform_method_v<Transformer, FromType, ToType>) {
                if (!Transformer::Transform(value, out)) {
                    return false;
                }
            } else {
                out = value;
            }
        } else {
            if (!Transformer::Transform(value, out)) {
                return false;
            }
        }
        return true;
    }

    static bool ApplyConversion(const FromType& value, ToType& out)
    {
        using namespace ValueTransformerTypeTraits;
        using Constraint = GEParamsConstraintInfo<Tag>;

        if constexpr (Constraint::HAS_CONVERT) {
            if constexpr (Constraint::HAS_CUSTOM) {
                if (!TransformCustomConvert(value, out)) {
                    return false;
                }
            } else if constexpr (std::is_same_v<FromType, ToType>) {
                out = value;
            } else if constexpr (is_shared_ptr_v<FromType> && is_shared_ptr_v<ToType>) {
                out = std::static_pointer_cast<typename ToType::element_type>(value);
            } else {
                out = static_cast<ToType>(value);
            }
        } else if constexpr (std::is_same_v<FromType, ToType>) {
            out = value;
        } else {
            static_assert(sizeof(FromType) == 0, "Unsupported conversion from FromType to ToType");
            return false;
        }
        return true;
    }

    static void ApplyRangeConstraints(ToType& out)
    {
        using Constraint = GEParamsConstraintInfo<Tag>;

        if constexpr (Constraint::HAS_RANGE) {
            if constexpr (Constraint::COMPONENT_WISE) {
                if constexpr (Constraint::HAS_MIN && Constraint::HAS_MAX) {
                    out = ApplyComponentWiseClamp(out, Constraint::MIN_COMPONENTS, Constraint::MAX_COMPONENTS);
                } else if constexpr (Constraint::HAS_MIN) {
                    out = ApplyComponentWiseMin(out, Constraint::MIN_COMPONENTS);
                } else if constexpr (Constraint::HAS_MAX) {
                    out = ApplyComponentWiseMax(out, Constraint::MAX_COMPONENTS);
                }
            } else {
                if constexpr (Constraint::HAS_MIN && Constraint::HAS_MAX) {
                    out = std::clamp(out, Constraint::MIN, Constraint::MAX);
                } else if constexpr (Constraint::HAS_MIN) {
                    out = std::max(out, Constraint::MIN);
                } else if constexpr (Constraint::HAS_MAX) {
                    out = std::min(out, Constraint::MAX);
                }
            }
        }
    }

    static bool Transform(const FromType& value, ToType& out)
    {
        if (!ApplyConversion(value, out)) {
            return false;
        }
        ApplyRangeConstraints(out);
        return true;
    }

private:
    static constexpr size_t AXIS_X = 0;
    static constexpr size_t AXIS_Y = 1;
    static constexpr size_t AXIS_Z = 2;
    static constexpr size_t AXIS_W = 3;

    static std::pair<float, float> ApplyComponentWiseClamp(
        const std::pair<float, float>& value, const float (&min)[2], const float (&max)[2])
    {
        return std::pair<float, float>(
            std::clamp(value.first, min[AXIS_X], max[AXIS_X]),
            std::clamp(value.second, min[AXIS_Y], max[AXIS_Y]));
    }

    static Vector2f ApplyComponentWiseClamp(const Vector2f& value, const float (&min)[2], const float (&max)[2])
    {
        return Vector2f(std::clamp(value.x_, min[AXIS_X], max[AXIS_X]),
                        std::clamp(value.y_, min[AXIS_Y], max[AXIS_Y]));
    }

    static Vector3f ApplyComponentWiseClamp(const Vector3f& value, const float (&min)[3], const float (&max)[3])
    {
        return Vector3f(std::clamp(value.x_, min[AXIS_X], max[AXIS_X]),
                        std::clamp(value.y_, min[AXIS_Y], max[AXIS_Y]),
                        std::clamp(value.z_, min[AXIS_Z], max[AXIS_Z]));
    }

    static Vector4f ApplyComponentWiseClamp(const Vector4f& value, const float (&min)[4], const float (&max)[4])
    {
        return Vector4f(std::clamp(value.x_, min[AXIS_X], max[AXIS_X]),
                        std::clamp(value.y_, min[AXIS_Y], max[AXIS_Y]),
                        std::clamp(value.z_, min[AXIS_Z], max[AXIS_Z]),
                        std::clamp(value.w_, min[AXIS_W], max[AXIS_W]));
    }

    template<typename T>
    static T ApplyComponentWiseMin(const T& value, const float (&min)[4])
    {
        if constexpr (std::is_same_v<T, Vector2f>) {
            return Vector2f(std::max(value.x_, min[AXIS_X]), std::max(value.y_, min[AXIS_Y]));
        } else if constexpr (std::is_same_v<T, Vector3f>) {
            return Vector3f(std::max(value.x_, min[AXIS_X]),
                            std::max(value.y_, min[AXIS_Y]),
                            std::max(value.z_, min[AXIS_Z]));
        } else if constexpr (std::is_same_v<T, Vector4f>) {
            return Vector4f(std::max(value.x_, min[AXIS_X]),
                            std::max(value.y_, min[AXIS_Y]),
                            std::max(value.z_, min[AXIS_Z]),
                            std::max(value.w_, min[AXIS_W]));
        } else {
            return value;
        }
    }

    static std::pair<float, float> ApplyComponentWiseMin(
        const std::pair<float, float>& value, const float (&min)[2])
    {
        return std::make_pair(std::max(value.first, min[AXIS_X]), std::max(value.second, min[AXIS_Y]));
    }

    template<typename T>
    static T ApplyComponentWiseMax(const T& value, const float (&max)[4])
    {
        if constexpr (std::is_same_v<T, Vector2f>) {
            return Vector2f(std::min(value.x_, max[AXIS_X]), std::min(value.y_, max[AXIS_Y]));
        } else if constexpr (std::is_same_v<T, Vector3f>) {
            return Vector3f(std::min(value.x_, max[AXIS_X]),
                            std::min(value.y_, max[AXIS_Y]),
                            std::min(value.z_, max[AXIS_Z]));
        } else if constexpr (std::is_same_v<T, Vector4f>) {
            return Vector4f(std::min(value.x_, max[AXIS_X]),
                            std::min(value.y_, max[AXIS_Y]),
                            std::min(value.z_, max[AXIS_Z]),
                            std::min(value.w_, max[AXIS_W]));
        } else {
            return value;
        }
    }

    static std::pair<float, float> ApplyComponentWiseMax(
        const std::pair<float, float>& value, const float (&max)[2])
    {
        return std::make_pair(std::min(value.first, max[AXIS_X]), std::min(value.second, max[AXIS_Y]));
    }
};

'''

CONSTRAINT_MACROS = r'''
// Constraint Metadata Macros for Min Component
#define GE_PARAMS_CONSTRAINT_MIN(Tag, Type, Min) \
    template<> \
    struct GEParamsConstraintMinInfo<GEParamsMemberTag::Tag> { \
        static constexpr bool HAS_MIN = true; \
        static constexpr bool COMPONENT_WISE = false; \
        static constexpr size_t COMPONENT_COUNT = 0; \
        static constexpr Type MIN = Min; \
    }

#define GE_PARAMS_CONSTRAINT_MIN_COMPONENTS(Tag, Type, Count, Mins) \
    template<> \
    struct GEParamsConstraintMinInfo<GEParamsMemberTag::Tag> { \
        static constexpr bool HAS_MIN = true; \
        static constexpr bool COMPONENT_WISE = true; \
        static constexpr size_t COMPONENT_COUNT = Count; \
        static constexpr Type MIN_COMPONENTS[] = Mins; \
    }

// Constraint Metadata Macros for Max Component
#define GE_PARAMS_CONSTRAINT_MAX(Tag, Type, Max) \
    template<> \
    struct GEParamsConstraintMaxInfo<GEParamsMemberTag::Tag> { \
        static constexpr bool HAS_MAX = true; \
        static constexpr bool COMPONENT_WISE = false; \
        static constexpr size_t COMPONENT_COUNT = 0; \
        static constexpr Type MAX = Max; \
    }

#define GE_PARAMS_CONSTRAINT_MAX_COMPONENTS(Tag, Type, Count, Maxs) \
    template<> \
    struct GEParamsConstraintMaxInfo<GEParamsMemberTag::Tag> { \
        static constexpr bool HAS_MAX = true; \
        static constexpr bool COMPONENT_WISE = true; \
        static constexpr size_t COMPONENT_COUNT = Count; \
        static constexpr Type MAX_COMPONENTS[] = Maxs; \
    }

// Constraint Metadata Macros for Convert Component
#define GE_PARAMS_CONSTRAINT_CONVERT_CAST_FROM(Tag, _CastFromType) \
    template<> \
    struct GEParamsConstraintConvertInfo<GEParamsMemberTag::Tag> { \
        static constexpr bool HAS_CONVERT = true; \
        static constexpr bool HAS_CAST_FROM = true; \
        using CastFromType = _CastFromType; \
        static constexpr bool HAS_CUSTOM = false; \
        using CustomTransformer = void; \
    }

#define GE_PARAMS_CONSTRAINT_CONVERT_CUSTOM(Tag, _CastFromType, _CustomTransformer) \
    template<> \
    struct GEParamsConstraintConvertInfo<GEParamsMemberTag::Tag> { \
        static constexpr bool HAS_CONVERT = true; \
        static constexpr bool HAS_CAST_FROM = true; \
        using CastFromType = _CastFromType; \
        static constexpr bool HAS_CUSTOM = true; \
        using CustomTransformer = _CustomTransformer; \
    }

'''

CONSTRAINT_MACRO_UNDEF = r'''
#undef GE_PARAMS_CONSTRAINT_MIN
#undef GE_PARAMS_CONSTRAINT_MIN_COMPONENTS
#undef GE_PARAMS_CONSTRAINT_MAX
#undef GE_PARAMS_CONSTRAINT_MAX_COMPONENTS
#undef GE_PARAMS_CONSTRAINT_CONVERT_CAST_FROM
#undef GE_PARAMS_CONSTRAINT_CONVERT_CUSTOM

'''


def generate_constraints(structs: List[StructInfo]):
    """Generate constraint macros and metadata"""
    output = []
    # Generate constraint specialization macros
    output.append(CONSTRAINT_MACROS)

    # Generate constraint metadata for constrained fields
    for struct in structs:
        for field in struct.fields:
            for tag_info in iterate_field_tags(struct, field):
                metadata = generate_constraint_metadata(field, tag_info.tag_name, tag_info.prop_attr_index)
                if metadata:
                    output.append(metadata)

    output.append(CONSTRAINT_MACRO_UNDEF)
    return "\n".join(output)


def generate_header(structs: List[StructInfo], type_aliases: Dict[str, str], blocked_types: Dict[str, str] = None) -> str:
    """Generate the complete header file."""
    if blocked_types is None:
        blocked_types = {}

    output = []

    output.append(COPYRIGHT_HEADER)
    output.append("")
    output.append("#ifndef GRAPHICS_EFFECT_GE_PARAMS_REFLECTION_H")
    output.append("#define GRAPHICS_EFFECT_GE_PARAMS_REFLECTION_H")
    output.append("")
    output.append("#include <algorithm>")
    output.append("#include <cmath>")
    output.append("#include <cstdint>")
    output.append("#include <optional>")
    output.append("#include <string>")
    output.append("#include <string_view>")
    output.append("#include <type_traits>")
    output.append("#include <utility>")
    output.append("")
    output.append('#include "ge_effects_params.h"')
    output.append('#include "ge_value_transformer_traits.h"')
    output.append('#include "ge_value_transformer.h"')
    output.append("")

    output.append("namespace OHOS {")
    output.append("namespace Rosen {")
    output.append("namespace Drawing {")
    output.append("")
    output.append("class GEFilterParams;")
    output.append("")

    output.append("// Helper macro to escape commas in macro arguments")
    output.append("// e.g. CALL(std::pair<int, int>), the comma would separate into two macro arguments")
    output.append("//      CALL(ESCAPE(std::pair<int, int>)) treats it as one argument")
    output.append("// Used to pass types as-is without extra parentheses which can cause issues in some contexts")
    output.append("#define ESCAPE(...) __VA_ARGS__")
    output.append("")

    output.append(generate_type_xmacro(structs, type_aliases, blocked_types))

    # Generate member enums first (before base templates, so no forward declaration needed)
    enum_code, struct_tag_ranges = generate_member_enums(structs)
    output.append(enum_code)

    # Generate base constraint templates (after enum, so GEParamsMemberTag is defined)
    output.append(BASE_CONSTRAINT_TEMPLATES)

    # Generate GEParamsValueTransformer template
    output.append(VALUE_TRANSFORMER_TEMPLATE)

    # Generate constraint specializations
    output.append(generate_constraints(structs))

    # Generate GEFilterParamsTypeInfo specializations
    output.append(generate_filter_params_type_info(structs))
    output.append(generate_params_builder_decl())

    # Generate type traits
    output.append(generate_type_traits(structs))

    # Generate GEParamsMemberHelper declaration (includes SetParamsMemberByTag template)
    output.append(generate_struct_tag_ranges_decl(structs, type_aliases, blocked_types))

    output.append("} // namespace Drawing")
    output.append("} // namespace Rosen")
    output.append("} // namespace OHOS")
    output.append("")
    output.append("#endif // GRAPHICS_EFFECT_GE_PARAMS_REFLECTION_H")

    return "\n".join(output)


def generate_cpp(structs: List[StructInfo], type_aliases: Dict[str, str], blocked_types: Dict[str, str] = None) -> str:
    """Generate complete cpp file."""
    if blocked_types is None:
        blocked_types = {}

    output = []

    output.append(COPYRIGHT_HEADER)
    output.append("")
    output.append('#include "ge_params_reflection.h"')
    output.append('#include "ge_filter_params.h"')
    output.append('#include "ge_log.h"')
    output.append("#include <unordered_map>")
    output.append("")

    output.append("namespace OHOS {")
    output.append("namespace Rosen {")
    output.append("namespace Drawing {")
    output.append("")

    # Generate GEParamsBuilder::Build() implementation
    output.append(generate_params_builder_impl(structs))

    # Generate GEParamsBuilder::GetFilterTypeFromString() implementation
    output.append(generate_filter_type_from_string_impl(structs))

    # Generate GEParamsMemberHelper::GetFilterTypeFromTag() implementation
    output.append(generate_get_filter_type_from_tag_impl(structs))

    # Generate GEParamsMemberTagFromString() implementation
    output.append(generate_string_to_enum_mapping_impl(structs))

    # Generate overloaded SetParamsMemberByTag implementations
    output.append(generate_set_params_member_overloads_impl(structs, type_aliases, blocked_types))

    output.append("} // namespace Drawing")
    output.append("} // namespace Rosen")
    output.append("} // namespace OHOS")
    output.append("")

    return "\n".join(output)


def check_unused_enum_values(structs: List[StructInfo], type_aliases: Dict[str, str], blocked_types: Dict[str, str] = None) -> None:
    """Check for enum values that are not referenced in any SetParamsMemberByTag implementation.

    This can happen when a type is in member_setter_blocked_types, which prevents
    SetParamsMemberByTag overloads from being generated for that type.

    Args:
        structs: List of struct information
        type_aliases: Type alias mapping
        blocked_types: Dictionary of types to exclude
    """
    if blocked_types is None:
        blocked_types = {}

    all_tags = set()
    referenced_tags = set()
    tag_to_info = {}

    for struct in structs:
        for field in struct.fields:
            for tag_info in iterate_field_tags(struct, field):
                all_tags.add(tag_info.tag_name)
                tag_to_info[tag_info.tag_name] = (struct, field, tag_info)

                normalized_type = get_effective_type_for_tag(
                    field, tag_info.is_array_element, tag_info.array_index, tag_info.prop_attr_index, type_aliases
                )

                if normalized_type not in blocked_types:
                    referenced_tags.add(tag_info.tag_name)

                if has_cast_from(field, tag_info.prop_attr_index):
                    original_type = get_original_field_type(field, tag_info.is_array_element)
                    normalized_original = normalize_type(original_type, type_aliases)

                    if normalized_original not in blocked_types:
                        referenced_tags.add(tag_info.tag_name)

    unused_tags = all_tags - referenced_tags

    if unused_tags:
        console.warning("Found enum values not referenced in any SetParamsMemberByTag implementation:")
        for tag in sorted(unused_tags):
            if tag not in tag_to_info: # should never happen since all_tags is built with tag_to_info
                continue
            struct, field, tag_info = tag_to_info[tag]
            normalized_type = get_effective_type_for_tag(
                field, tag_info.is_array_element, tag_info.array_index, tag_info.prop_attr_index, type_aliases
            )
            reason = blocked_types.get(normalized_type, "unknown reason")
            console.step(f"  {tag} ({struct.name}::{field.name}) - type '{normalized_type}' is blocked: {reason}")


def main():
    """Main generation function."""
    parser = argparse.ArgumentParser(
        description="Generate C++ static reflection metadata from .params files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python gen_metadata.py
  python gen_metadata.py --params-dirs custom/filter custom/maz --output-file custom/reflection.h
        """,
    )

    parser.add_argument(
        "--params-dirs",
        type=str,
        nargs="+",
        default=None,
        help="Directories containing .params files (default: include/effect/filter include/effect/mask include/effect/shader include/effect/shape)",
    )

    parser.add_argument("--output-file", type=str, default=None, help="Output header file path (default: include/effect/ge_params_reflection.h)")

    parser.add_argument("--output-cpp-file", type=str, default=None, help="Output cpp file path (default: src/effect/ge_params_reflection.cpp)")

    parser.add_argument("--config-file", type=str, default=None, help="Config file path (default: tool/generate_metadata/config.json)")

    parser.add_argument(
        "--effect-dirs",
        type=str,
        nargs="+",
        default=None,
        help="Directories containing effect header files (default: include/effect/filter include/effect/mask include/effect/shader include/effect/shape)",
    )

    args = parser.parse_args()

    root_dir = Path(__file__).parent.parent.parent

    if args.params_dirs:
        params_dirs = [Path(d) for d in args.params_dirs]
    else:
        params_dirs = [
            root_dir / "include" / "effect" / "filter",
            root_dir / "include" / "effect" / "mask",
            root_dir / "include" / "effect" / "shader",
            root_dir / "include" / "effect" / "shape",
        ]
    output_file = Path(args.output_file) if args.output_file else root_dir / "include" / "effect" / "ge_params_reflection.h"
    output_cpp_file = Path(args.output_cpp_file) if args.output_cpp_file else root_dir / "src" / "effect" / "ge_params_reflection.cpp"
    config_file = Path(args.config_file) if args.config_file else Path(__file__).parent / "config.json"

    if args.effect_dirs:
        effect_dirs = [Path(d) for d in args.effect_dirs]
    else:
        effect_dirs = [
            root_dir / "include" / "effect" / "filter",
            root_dir / "include" / "effect" / "mask",
            root_dir / "include" / "effect" / "shader",
            root_dir / "include" / "effect" / "shape",
        ]

    console.header("Loading configuration")
    type_aliases, blocked_types = load_config(config_file)
    console.info(f"Loaded {len(type_aliases)} type aliases from {config_file}")
    if blocked_types:
        console.info(f"Loaded {len(blocked_types)} blocked types from {config_file}")
        for blocked_type, reason in blocked_types.items():
            console.step(f"  Blocked: {blocked_type} - {reason}")

    console.header("Scanning for .params files")
    params_files = []
    for params_dir in params_dirs:
        params_files.extend(list(params_dir.glob("*.params")))
    params_files.sort(key=lambda p: p.name)

    if not params_files:
        console.error(f"No .params files found in {params_dirs}")
        console.summary()
        return 1

    console.info(f"Found {len(params_files)} .params files in:")
    for params_dir in params_dirs:
        console.step(f"{params_dir}")

    console.header("Parsing params definition files")
    structs = []
    for params_file in params_files:
        struct_info = parse_def_file(params_file)
        if struct_info:
            structs.append(struct_info)
            console.step(f"Parsed: {struct_info.name}")
        else:
            console.warning(f"Failed to parse {params_file.name}")

    if not structs:
        console.error("No valid structs found!")
        console.summary()
        return 1

    console.info(f"Parsed {len(structs)} structs with {sum(len(s.fields) for s in structs)} total fields")

    console.header("Scanning for DECLARE_GEFILTER_TYPEFUNC macros")
    macro_infos = scan_declare_gefilter_typefunc(effect_dirs)
    console.info(f"Found {len(macro_infos)} DECLARE_GEFILTER_TYPEFUNC macros")

    for info in macro_infos:
        console.step(f"{info.filter_class} -> {info.params_type}")

    console.header("Generating reflection metadata")
    console.step(f"Generating {output_file.name}...")
    header_content = generate_header(structs, type_aliases, blocked_types)

    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(header_content)

    console.file(f"Generated {output_file}")
    console.info(f"  - {len(structs)} parameter types")
    console.info(f"  - {sum(len(s.fields) for s in structs)} total fields")

    console.step(f"Generating {output_cpp_file.name}...")
    cpp_content = generate_cpp(structs, type_aliases, blocked_types)

    output_cpp_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_cpp_file, "w", encoding="utf-8") as f:
        f.write(cpp_content)

    console.file(f"Generated {output_cpp_file}")

    # Format generated files with clang-format if available
    clang_format_path = find_clang_format()
    if clang_format_path:
        console.header("Formatting generated files")
        format_file_with_clang_format(output_file, clang_format_path, console)
        format_file_with_clang_format(output_cpp_file, clang_format_path, console)
    else:
        console.warning("clang-format not found. Generated files will not be formatted.")
        console.step("Install clang-format to enable automatic formatting.")

    console.step(f"Found {len(macro_infos)} filter type info specializations")

    check_unused_enum_values(structs, type_aliases, blocked_types)

    console.summary()
    return 0 if console.error_count == 0 else 1


if __name__ == "__main__":
    exit(main())
